requirements/base.txt

@awais786 
Update base requirements for django, `django==1.8.7`

use django version '1.8.7' for base requirements

---

credentials/settings/local.py
credentials/settings/production.py
credentials/settings/test.py
credentials/settings/utils.py

Add logger settings in `settings/utils.py` and import/use it in `local`, `test` and `production` settings.
@awais786 @ahsan-ul-haq @tasawernawaz @waheedahmed

add logger config in settings

---

credentials/settings/devstack.py

add debug level logger for `devstack` settings.
@awais786 @ahsan-ul-haq @tasawernawaz @waheedahmed

add debug logger for devstack settings

---

credentials/apps/api/accreditors.py
credentials/apps/api/exceptions.py
credentials/apps/api/models.py
credentials/apps/api/serializers.py
credentials/apps/api/tests/factories.py
credentials/apps/api/tests/test_accreditors.py
credentials/apps/api/tests/test_serializers.py
credentials/apps/api/tests/test_views.py
credentials/apps/api/v1/urls.py
credentials/apps/api/v1/views.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_issuer.py
credentials/apps/credentials/tests/test_models.py
credentials/apps/credentials/tests/test_utils.py
credentials/apps/credentials/utils.py
credentials/settings/base.py
requirements/base.txt
requirements/test.txt

ECOM-2999
* Adding the end-points to create the user credentials.
* Patch functionality to update the status.
* Classes implementation.
* /api/v1/credentials/: List all credentials
* /api/v1/credentials/:id/: Retrieve a single credential
* Added filtering to your list endpoint: /api/v1/credentials/?username=<username>&status=<status>.
Reference: https://github.com/edx/edx-platform/commit/84699260e06199b8a41c3765260dc35cf619e4c1
Filtering for Programs and Courses will be added in separate story [ECOM-3263](https://openedx.atlassian.net/browse/ECOM-3263).

User Credentials api

---

credentials/apps/api/v1/urls.py

@clintonb I have tried to fetch the data using this URL in lms [here](https://github.com/edx/edx-platform/pull/11064/files#diff-ad7d61197fa94d2095dccbb82e6ab748R39) but I got error as hyphen is not allowed so I change it. Is that okay or would you suggest something else?
FYI: @awais786 @zubair-arbi

change url from hyphen to underscore

---

credentials/apps/api/serializers.py
credentials/apps/api/tests/test_views.py

ECOM-2999
Please review this. I have fixed issue of `read_only_feilds` in user credential update API.
@ahsan-ul-haq @awais786 @zubair-arbi

Fixed bug in 'read_only_fields' of credential update API.

---

credentials/apps/api/filters.py
credentials/apps/api/tests/test_views.py
credentials/apps/api/v1/urls.py
credentials/apps/api/v1/views.py
credentials/apps/credentials/models.py

ECOM-3263
Added following filters end points for program and course credentials.
* `/api/v1/program_credentials/?program_id=<program_id>`
* `/api/v1/program_credentials/?program_id=<program_id>&status=<status>`
* `/api/v1/course_credentials/?course_id=<course_id>`
* `/api/v1/course_credentials/?course_id=<course_id>&status=<status>`
* `/api/v1/course_credentials/?course_id=<course_id>&certificate_type=<certificate_type>`
Please review this @zubair-arbi @ahsan-ul-haq @awais786

Added filter for program and course credentials APIs.

---

credentials/apps/api/serializers.py
credentials/apps/api/tests/factories.py
credentials/apps/api/tests/test_accreditors.py
credentials/apps/api/tests/test_serializers.py
credentials/apps/api/tests/test_views.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/migrations/0001_initial.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_issuer.py
credentials/apps/credentials/tests/test_utils.py
credentials/apps/credentials/utils.py
docs/credentials_api.rst

ECOM-3418
* Removed field `namespace` from credentials attributes.
* Updated relevant tests.
* Added migration.
Please review this @zubair-arbi @ahsan-ul-haq @awais786

Removed field namespace from credential attributes

---

docs/credentials_api.rst

@ahsan-ul-haq @tasawernawaz @awais786 
* For now the docs are not displaying code example and I believe that we need to provide the type to `code-block` parameter.
* Update input example for create user credential endpoint in docs.

provide type for code-block examples in docs

---

credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/static/js/credentials/print.js
credentials/templates/base.html
credentials/templates/credentials/base.html
credentials/templates/credentials/program_certificate.html
credentials/templates/credentials/render_credential.html

ECOM-3284
* Adding base template for credentials.
* Add the updated HTML from webcert for XSeries certificates. 
* Adding dynamic values from db and relevant apis e.g organization api, programs api, users api.
HTML is picked from this repo
https://github.com/edx/web-certificates/blob/master/templates/xseries-base.html
Credential Template
Print version

Adding HTML for credential rendering.

---

Makefile

Limited output may be nice for local development, but is frustrating for failed runs non-development environments. Developers can live with extra output.

Increased verbosity of static files commands

---

credentials/settings/base.py

Add default css filter `CssAbsoluteFilter` from django compressor to base settings to resolve the issue of bower static files paths in css on production.

add default css filter in base settings

---

requirements/base.txt

Update python memcache version as previous version was causing error while compression. 
Here is error 
```python
1216 static files copied to '/edx/var/credentials/staticfiles', 83 unmodified.
python manage.py compress
Found 'compress' tags in:
/edx/app/credentials/credentials/credentials/templates/credentials/base.html
/edx/app/credentials/credentials/credentials/templates/credentials/render_credential.html
/edx/app/credentials/credentials/credentials/templates/base.html
Compressing... CommandError: An error occurred during rendering /edx/app/credentials/credentials/credentials/templates/credentials/base.html: int() argument must be a string or a number, not 'NoneType'
```
@zubair-arbi @tasawernawaz @tasawernawaz

python mamcache version update

---

requirements/base.txt

* add version for libsass `libsass==0.10.0`
_Background: The setup of `django-libsass` requires `"libsass>=0.7.0"` and the newest version `libsass==0.10.1` gives validation error on importing variables in scss files:_
```
Compressing... CommandError: An error occurred during rendering /Users/zubairafzal1/Workspace/devstack/credentials/credentials/templates/credentials/base.html: Error: Import directives may not be used within control directives or mixins.
on line 12 of credentials/static/sass/_lib.scss
>>     @import '../bower_components/bi-app-sass/bi-app/bi-app-rtl';
----^
```

add version for libsass

---

credentials/apps/api/tests/factories.py
credentials/apps/core/context_processors.py
credentials/apps/core/tests/test_context_processors.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/settings/base.py
credentials/templates/credentials/base.html
credentials/templates/credentials/program_certificate.html

ECOM-3557
* Show `title` from the program certificate configurations if set, instead of the program name while rendering the certificate
* User site configuration for linking to its lms url
* Add/Update test for above changes
_Old PR: https://github.com/edx/credentials/pull/49_

add certificate title override

---

credentials/apps/core/tests/test_views.py
credentials/apps/core/views.py
credentials/templates/404.html
credentials/templates/500.html
credentials/templates/base.html
credentials/templates/header.html
credentials/urls.py

ECOM-3527
* add `404.html` page 
* add `500.html` page 
* add urls for 404 and 500 pages

add basic templates for 404 and 500 pages

---

credentials/static/sass/_layouts.scss

@marcotuts @ahsan-ul-haq 
This change takes us from here:
To here:

Remove unnecessary padding above print cert icon

---

credentials/settings/production.py
credentials/static/sass/_config.scss

ECOM-3605
* Remove settings for S3 as these settings will come from configuration https://github.com/edx/configuration/pull/2758/
* Fix the images path in file `_config.scss` to work with S3
Sample S3 config settings:
```yml
AWS_STORAGE_BUCKET_NAME: mybucket
AWS_CUSTOM_DOMAIN: mybucket.s3.amazonaws.com
AWS_ACCESS_KEY_ID: XXXAWS_ACCESS_KEYXXX
AWS_SECRET_ACCESS_KEY: XXXAWS_SECRETY_KEYXXX
AWS_QUERYSTRING_AUTH: False
AWS_QUERYSTRING_EXPIRE: False
AWS_DEFAULT_ACL: ''
AWS_HEADERS:
Cache-Control: max-age-31536000
Access-Control-Allow-Origin: PUT YOUR HOSTNAME HERE
COMPRESS_URL: 'https://mybucket.s3.amazonaws.com/'
STATIC_URL: 'https://mybucket.s3.amazonaws.com/'
COMPRESS_ROOT: {{ CREDENTIALS_STATIC_ROOT }}
COMPRESS_STORAGE: …
```

static files s3 settings

---

.coveragerc
credentials/apps/core/s3utils.py

@awais786 @ahsan-ul-haq @tasawernawaz @waheedahmed 
Update S3BotoStorage to use 'media' folder for media files and 'staticfiles' for static files.
Related configuration changes: https://github.com/edx/configuration/pull/2781
http://stackoverflow.com/questions/10390244/how-to-set-up-a-django-project-with-django-storages-and-amazon-s3-but-with-diff/10825691#10825691
http://martinbrochhaus.com/s3.html

add S3BotoStorage for static and media files

---

credentials/apps/core/s3utils.py
requirements/base.txt
requirements/production.txt

This reverts commit d60176274186825ed9d71ecdf8697681f1932946.
The workaround we needed was in configuration all along, but had the wrong name (fixed in https://github.com/edx/configuration/pull/2840)

Revert "use leonsim's fork of boto for fixing aws querysting issue"

---

bower.json

ECOM-3826
@awais786 @tasawernawaz @waheedahmed 
* bumped the `ux-pattern-library` version from `0.8.5` to `0.10.4`.
* The older version was giving error for missing [edx-icons svg files in the fallback-img directory](https://github.com/edx/ux-pattern-library/tree/master/pattern-library/fonts/edx-icons/fallback-img) when we try to use [django's storage backend 'ManifestStaticFilesStorage'](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#manifeststaticfilesstorage) for versioning of static files.
```
Post-processing 'build/bower_components/edx-pattern-library/pattern-library/css/edx-pattern-library-ltr.css' failed!
Traceback (most recent call last):
File "manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File …
```

update version for ux-pattern-library

---

credentials/settings/production.py

In some cases, such as when using Django's ManifestStaticFilesStorage, these settings must be different.
@jimabramson @maxrothman @zubair-arbi @awais786

Avoid setting COMPRESS_STORAGE equal to STATICFILES_STORAGE

---

credentials/apps/api/tests/test_views.py
credentials/apps/api/v1/views.py

ECOM-3978
Previously anonymous users can access the end point and get all credentials information. Now only Authenticated users can access the endpoint.
For sharing purpose rendering credential is already open for all users. So sharing will work.

Only authenticated users can acccess the list end point.

---

credentials/apps/api/serializers.py
credentials/apps/api/tests/factories.py
credentials/apps/api/tests/test_serializers.py
credentials/apps/api/tests/test_views.py

Adding checks so that only active ProgramCertificate configurations can generate credentials. I have added check for CourseCertificates too.
https://openedx.atlassian.net/browse/ECOM-3858

Adding check only active programs can generate credentials.

---

credentials/apps/api/permissions.py
credentials/apps/api/tests/test_views.py
credentials/apps/api/v1/views.py
credentials/apps/core/migrations/0003_auto_20160331_0218.py
credentials/settings/base.py
requirements/test.txt

ECOM-3978
@ahsan-ul-haq @awais786 @rlucioni  please review.

Fix model permissions for UserCredential.

---

Makefile
docker-compose.yml
requirements/base.txt

ECOM-3180
@awais786 @ahsan-ul-haq @tasawernawaz @waheedahmed 
*  Update `docker-compose.yml` to use [version 2 format](https://docs.docker.com/compose/compose-file/#version-2)
* Add base credentials for mysql container

update docker-compose file to use version 2 format

---

credentials/apps/credentials/migrations/0003_programcertificate_use_org_name.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/templates/credentials/program_certificate.html

[ECOM-4198] (https://openedx.atlassian.net/browse/ECOM-4198)
In order to support the existing use of wrapper-organizations such as VJx, added the ability to override the issuing organization on credentials (specifically XSeries, as courses already have this.)

Added ability to override issuing organization for credentials.

---

requirements/base.txt

@waheedahmed @ahsan-ul-haq @tasawernawaz @awais786 
* Bump `edx-auth-backends` from version `0.2.1` to `0.2.3`
* Remove `python-social-auth` pin at version `0.2.14` due to the latest version `0.2.19`
FYI: @clintonb @rlucioni

bump edx-auth-backends and remove python-social-auth pinning

---

requirements/base.txt

Django 1.8.15 fixes a security issue in 1.8.14. Release notes are at https://docs.djangoproject.com/en/1.10/releases/1.8.15.
@edx/ecommerce FYI.

Upgrade Django to 1.8.15

---

.tx/config

Credentials has no djangojs.po.
@clintonb please review. @edx/ecommerce FYI.

Update Transifex config to avoid searching for nonexistent PO file

---

Makefile

Transifex's Python client [compares last-modified timestamps](https://github.com/transifex/transifex-client/blob/master/txclib/project.py#L1009) to decide whether to download a file. This comparison might work great if you weren't using version control and only ever worked with one copy of the files. However, if you're using Git and clone this repo any time after new translations have been contributed by translators on Transifex, the client will never download new translations for you, since your files appear to have been modified after those on Transifex.
Forcing the client to download all files is a bit crude, but necessary until we can contribute a patch for the Transifex client.
@edx/ecommerce

Force Transifex client to download translations

---

Makefile

This repo has no djangojs source.

Avoid attempting to validate non-existent translations

---

requirements/base.txt

This version of the package limits the installed version of PSA to <0.3.0. 0.3.0 introduced a major breaking change, effectively gutting PSA and moving its Django components to a new social-auth-app-django package.
@edx/ecommerce @jibsheet FYI. This is follow-up to https://github.com/edx/auth-backends/pull/27 and should fix CI builds.

Upgrade edx-auth-backends to 0.5.3

---

credentials/static/sass/_layouts-rendering.scss
credentials/static/sass/_print-rendering.scss

The program type logos and edx logo were too big, so this makes them smaller. 
@edx/ecommerce

Tweak program type logo css

---

credentials/templates/credentials/program.html

Site operators control signatory data (i.e., it's not possible for a user to create or modify this content). Not escaping this prevents names like 'King's College' from becoming 'King&#39;s College' in the rendered credential.
@edx/ecommerce FYI. I caught this after seeing https://travis-ci.org/edx/credentials/builds/190417135#L1134 failing on master. Thanks Faker!

Avoid escaping signatory data

---

credentials/apps/api/v1/views.py
credentials/settings/base.py

All of our APIs should use page number pagination. This is now the default for the project. API v1 still retains limit-offset pagination to avoid breaking existing clients.
ECOM-6808

Corrected pagination class for API v2

---

credentials/apps/credentials/exceptions.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_models.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/templates/credentials/programs/base.html

ECOM-6863
Adding exception if logo image is missing in the program details.  This is expected to only be shown to PCs and edX staff during certificate configuration and is not likely to be learner-facing.
@edx/ecommerce for review

Adding exception throwing if logo image is missing

---

requirements/production.txt

This fixes a bug in the Ansible provisioning process where an existing nodeenv could fail to be created when the node version was changed.
See edx/configuration#3648 and ekalinin/nodeenv#183 for more details.

Upgrade nodeenv to 1.1.1

---

Makefile

Updated makefile to only pull reviewed strings from Transifex.
Verification of upcoming commit that will run by the jenkins job. https://github.com/edx/credentials/pull/181
Context:
The jenkins job that automatically pulls and merges translations from Transifex, but will create a PR in case it requires manual resolution. https://github.com/edx/credentials/pull/167 . Rather than manually fixing each string (there many of them), this PR changes the pull step to only pull strings that have been reviewed. Since there are no user facing translations in use, the changes https://github.com/edx/credentials/pull/181 should not effect the UX when removing the non-reviewed translations. The process for reviewing translations does not have to be resolved in this PR. By only pulling reviewed strings, …

Updated makefile to only pull reviewed strings from Transifex

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/views.py

@mjfrey @vkaracic @iivic This is the PR for making the User Credential API endpoint (WL) site aware.
The only reason this is marked as WIP is the fact that we still don't know to what extent should the endpoint be site-aware. I made it absolutely site-aware, which means that it doesn't matter which user sends the request to the endpoint, but from which Site the request is being sent from.
If we decide to remove the Site awareness for a specific use case, this PR can easily be modified.
JIRA ticket: https://openedx.atlassian.net/browse/ECOM-7345

[ECOM-7345] User Credential API endpoint should be site aware

---

credentials/static/js/sharing.js
package.json

Facebook offers an integration method that does not rely on jQuery. This integration is now used, and jQuery has been removed.
ECOM-6578

Removed jQuery

---

credentials/apps/api/v2/tests/test_serializers.py
credentials/apps/core/tests/test_commands.py
credentials/apps/credentials/tests/test_views.py

assertRaisesRegexp() was renamed to assertRaisesRegex()
Unblocks https://github.com/edx/credentials/pull/202.

Fix use of deprecated assert method

---

credentials/urls.py
requirements/base.txt

- Updated urls.py to use functions and classes instead of strings to
represent views
- Upgraded django-extensions to a version that avoids SubfieldBase

Resolved most Django 1.10 deprecation warnings

---

credentials/apps/core/tests/test_views.py
credentials/apps/core/views.py
credentials/apps/edx_django_extensions/tests/test_views.py
credentials/settings/base.py
credentials/settings/production.py
credentials/templates/500.html

- Removed USE_X_FORWARDED_HOST setting, since it is not the solution to our problem
- Set SITE_ID to None to ensure the middleware is always used to determine the current site
LEARNER-516

Fixes for multi-tenancy

---

credentials/apps/core/middleware.py
credentials/apps/core/tests/test_middleware.py
credentials/apps/core/tests/test_views.py
credentials/settings/base.py

This will allow our load balancers to come online properly without our
needing to modify configuration every time we deploy a new site.
LEARNER-516

Added middleware to exempt the health check from site checks

---

.gitignore
Makefile
credentials/settings/test.py
pytest.ini
requirements/test.txt

Having been in maintenance mode for the past several years, nose is effectively dead. edX and the Python community at large are moving towards pytest. pytest is actively developed and provides several benefits over nose, including detailed introspection of failing assert statements (no need to use unittest's assert methods), a rich plugin ecosystem, and modular fixtures (which may help move us away from relying on migrations for populating initial test data).

Use pytest to run tests

---

credentials/settings/base.py
requirements/base.txt

We don't need this app since nginx handles CORS headers for us.

Revert "Added django-cors-headers"

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/views.py

The switch supporting the disabling of site filtering has been removed. This service is now fully multi-tenant.
LEARNER-1102

Permanently enabled API site filtering

---

Makefile

The durations of the 25 slowest tests will now be printed. This should aid identifying long-running tests.

Printing Test Durations

---

credentials/apps/api/tests/test_views.py
credentials/apps/api/views.py
credentials/settings/base.py
credentials/static/css/edx-swagger.css
credentials/templates/rest_framework_swagger/index.html
credentials/urls.py
requirements/base.txt

The API docs were broken by the Django 1.11 upgrade. This change includes an upgrade to the most recent version of django-rest-swagger that supports DRF 3.4. Newer versions of django-rest-swagger require DRF 3.5.
LEARNER-1590
@edx/learner FYI

Fix API docs

---

credentials/apps/api/views.py
credentials/settings/base.py
requirements/base.txt

3.5.4 features improved schema generation, including the ability to exclude views from generated schemas. 3.5.4 deprecates DjangoFilterBackend in favor of the implementation provided by the django-filter package.
LEARNER-1590
@edx/learner FYI.

Upgrade to DRF 3.5.4

---

credentials/settings/base.py

This fixes an issue which prevents the browseable API from rendering. For more details, see https://github.com/carltongibson/django-filter/issues/562/#issuecomment-291035404.
LEARNER-1590
@edx/learner FYI.

Include django_filters in INSTALLED_APPS

---

requirements/base.txt

Changes for the new certs have been made in the themes repo and the
credential service needs to start using these changes.
[WL-1119]
[WL-1164]

Update credentials-themes repo in requirements

---

requirements/base.txt

Updates credentials-themes dependency to take advantage of work done for https://github.com/edx/credentials-themes/pull/14 to make translations for templates/partials available.
JIRA: https://openedx.atlassian.net/browse/LEARNER-1940

LEARNER-1940-Update edx-credentials-themes dependency

---

credentials/apps/credentials/views.py
credentials/apps/credentials_theme_openedx/static/sass/_components-rendering.scss

[LEARNER-3070](https://openedx.atlassian.net/browse/LEARNER-3070)
Adds in a11y fixes for templates (contrast ratio fix and empty HTML lang attribute for example certs)
FYI: @edx/learner-heart

LEARNER-3070: adds in dark styling for a11y issues

---

.travis.yml

Tests might be failing because of the verbose deprecation error output when compiling assets. This PR pipes the output to `/dev/null`. If `make static` fails, the build will still fail.

Remove verbose output for travis step

---

credentials/settings/base.py
credentials/tests/test_urls.py
credentials/urls.py
requirements/base.txt

https://openedx.atlassian.net/browse/ARCH-93
**Sandbox:** https://credentials-swagger.sandbox.edx.org/api-docs/

ARCH-93 Use django-rest-swagger to generate API documentation.

---

credentials/apps/credentials/tests/test_views.py
credentials/apps/records/views.py
credentials/settings/base.py
credentials/settings/devstack.py
credentials/templates/base.html

Make sure that the <html lang=""> tag is set for new Student Records work.
I also cleaned up a few instances of using en-us as the fallback language code. Our locale generated for English is 'en' not 'en-us' and in production, we already configure 'en' as the fallback. So devstack should be in sync too.

Set HTML lang tag for records pages

---

credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/utils.py
credentials/apps/credentials/views.py

Don't pass our templates a locale, instead make sure it's a language code (es-419 instead of es_419).
Annoyingly, django doesn't expose their own to_language implementation, only their to_locale implementation. They expect you to get language codes from their translation objects. But that's not what we have here. So I just made a function, it's simple enough.
I'll come back with a second PR to add a new Spanish example cert to help avoid testing gaps like this in the future.
https://openedx.atlassian.net/browse/LEARNER-5347

Fix 500s on Spanish certificates

---

credentials/apps/records/views.py

The fake links from My Records to individual records pages was not working because they weren't valid uuids. Fixed that. You still don't get real content, but at least the flow is correct now.

Fix records links

---

Makefile

Fix static asset compilation to happen at right time. I tried to simplify the rules in an earlier commit. But that mucked with the ordering. Whoops.

Fix static compilation

---

.travis.yml
credentials/apps/credentials_theme_openedx/static/sass/_components-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_config.scss
credentials/apps/credentials_theme_openedx/static/sass/_layouts-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_lib.scss
credentials/apps/credentials_theme_openedx/static/sass/_utilities.scss
credentials/static/sass/_components.scss
credentials/static/sass/_config.scss
credentials/static/sass/_layouts.scss
credentials/static/sass/_lib.scss
credentials/static/sass/_utilities.scss
credentials/static/sass/_views.scss
package.json

Start using bootstrap instead of edx-pattern-library in a few places. We eventually want to get rid of the pattern library altogether. But baby steps.
This branch mostly just changes some base styling and bits of the openedx them to use less pattern-library code. I didn't touch the edx theme in credentials-themes.
I've tested this on mobile (firefox and safari) and desktop (firefox and chromium so far).
I've tested the openedx and edx.org themes. The edx.org one needed no changes, so I don't think we'll break any other custom themes.
I've tested by looking at the example certificate and also confirmed that we didn't break the early-stages records work we have.
I am using an old version of bootstrap (v4 alpha 6, which paragon used to use) because newer versions caused some conflicts with …

Use bootstrap a little bit

---

credentials/apps/api/accreditors.py
credentials/apps/api/docs/decisions/0001-post-as-update-or-create.md
credentials/apps/api/tests/test_accreditors.py
credentials/apps/api/v2/serializers.py
credentials/apps/api/v2/tests/test_serializers.py
credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/views.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py
credentials/settings/devstack.py

Support creating course certificates when a POST is made from the LMS.
This renames the API serialization of course_run_id to course_run_key, but that's fine, since that serialization is like a week old and no one is using it.
https://openedx.atlassian.net/browse/LEARNER-5050

Create course certs when asked

---

credentials/apps/core/tests/factories.py
credentials/apps/core/tests/test_utils.py
credentials/apps/core/utils.py
credentials/settings/base.py

We already synced the username and email, but we also want the full name, which we'll display on student records.
This isn't necessarily something we want to push upstream to EdxDjangoStrategy, because the full_name field is a Credentials addition. So not sure we can rely on that field being there for other IDAs.
https://openedx.atlassian.net/browse/LEARNER-5304

Sync full name on login

---

package.json

These were added during debugging of travis issues. I figure it doesn't hurt to take them out, but I suspect they will help unblock deploys.
@AlasdairSwan

Pull out other sass dependencies.

---

package.json

@AlasdairSwan I did a search for '~' and it seems like breakpoint was the only one missing, ironically enough.

Add in top-level sass dependencies.

---

credentials/static/components/ProgramRecord.jsx
credentials/static/components/Utils.jsx
credentials/static/components/specs/ProgramRecord.test.jsx

Added a boolean field to indicate whether the public or private view should be visible. It is private if the program record is associated with the current logged in user (checked via cookie), and public otherwise. This has been commented out to pass code coverage for now, will be used for LEARNER-5550.
Also added a utility function for parsing the 'edx-user-info' cookie as its JSON string contains escaped quotes and encoded commas which break JSON.parse().

Added check for public/private view

---

package-lock.json
package.json

A version mismatch for npm between devstack and builders is causing build problems. For now, just manually update package files using latest npm, until we fix devstack.
This is just a guess that it will fix GoCD. But it's likely?
Also, I have no idea why package-lock.json is updated so heavily. I'm just blindling trusting "npm install" to do the right thing here.

Update package*.json with latest npm

---

webpack.config.js

ManifestStaticFilesStorage on prod raising file not found error
for font awesome svg files. Fixed by not loading them inline and
use file-loader instead.
This issue started appearing after merging https://github.com/edx/credentials/pull/435.
LEARNER-5722

Fix font awesome svg inline loading in css.

---

credentials/static/components/Analytics.jsx
credentials/static/components/ProgramRecord.jsx
credentials/static/components/SendLearnerRecordModal.jsx
credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/components/specs/Analytics.test.jsx
credentials/static/components/specs/SendLearnerRecordModal.test.jsx
credentials/static/js/analytics.js

[LEARNER-5650](https://github.com/edx/credentials/tree/spencerhance/LEARNER-5650-add-records-analytics)
Implements all of the [new GA metrics](https://openedx.atlassian.net/wiki/spaces/AN/pages/779944554/Student+Records?focusedCommentId=789217308#comment-789217308) except for download_started and download_finished which need to be done in the Django API (via [LEARNER-5513](https://openedx.atlassian.net/browse/LEARNER-5513))

Adds records analytics

---

credentials/apps/records/tests/factories.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/urls.py
credentials/apps/records/views.py

- Created new url for public views
- Updated get_record() to work with public views (there's an extra layer)
- Updated the context data to pass along the is_public boolean to the front end for button rendering
- Updated tests, added ProgramCertRecord factory

Updated backend to support public views at separate URL

---

credentials/static/components/ProgramRecord.jsx
credentials/static/components/ProgramRecordFactory.jsx
credentials/static/components/Utils.jsx
credentials/static/components/specs/ProgramRecord.test.jsx
credentials/templates/programs.html

Previously the ProgramRecord view used a cookie to decide whether it should be public or private. This PR updates it to instead use a prop.

Updated front end to use public/private prop

---

Makefile

This is for dealing with issues within docker and running everything from the docker root.
Other places where this issue has been mentioned (along with this fix): https://github.com/npm/npm/issues/17431
https://github.com/sass/node-sass/issues/2006
We need a more robust solution, but this is blocking any updates to `package.json` or `package-lock.json`.

Handle node dependencies using --unsafe-perm.

---

.travis.yml

Saves an insignificant amount of time for overall time.
The main benefit we get is a clear split of what tests are being run.

Added travis matrix

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

Updates the ProgramRecordView get request to return all program courses, even if they don't have a grade or cert for any associated course_runs.
If they don't have a verified cert, all table values except for Course name and org are left blank.
Additionally, the _Course_ title is used instead of the Course _run_ title when there are no certs for the associated course runs.

Show all program courses in program record view

---

credentials/templates/programs.html
credentials/templates/records.html

Previously, in cases where a theme template exists, "default" blocks (without icons) for RecordsFactory and ProgramRecord factory were not getting overridden as expected when including the theme template. This meant that there were two calls for the factories on each page, rather than just the one for the themed template. This fixes that by only having the "default" blocks when the theme template doesn't exist. 
[LEARNER-5996](https://openedx.atlassian.net/browse/LEARNER-5996)

Prevent factory calls from getting included twice

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/records/constants.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/settings/base.py
credentials/shared/log_checker.py
requirements/base.txt
requirements/test.txt

[LEARNER-5925](https://openedx.atlassian.net/browse/LEARNER-5925) Adds django-ratelimit throttling to the credentials records endpoints.
Note:
At this time, we're not adding a higher rate limit for staff/superusers because these endpoints correspond to the share record and send record buttons, which staff should not be using much more frequently than regular users.

LEARNER-5925 Add rate limiting to credentials records endpoint

---

credentials/static/components/ShareProgramRecordModal.jsx

Fix the spelling of the edx.bi.credential.program_record.share_url_copied event to match the spelling of "credentials" in the other events.

Fix records share analytics event name

---

credentials/apps/records/views.py

If a user is not logged in to credentials, redirect them to a login page before checking if the waffle flag is enabled.  This is because we don't know if the user has the flag enabled until they are logged in.
If the site has the "Enable Learner Records" option turned off in the site config, the user will still be redirected to a login page before hitting a 404.
This also doesn't affect the public records view.

Fix Records Waffle Flag Login Redirect

---

requirements/base.txt

There is a vulnerability of phishing in django 1.11.11 announced by django community.To avoid it,upgrade current django version to 1.11.15 to overcome that vulnerability.
https://docs.djangoproject.com/en/2.0/releases/1.11.15/#cve-2018-14574-open-redirect-possibility-in-commonmiddleware

Upgrade django to 1.11.15 for security update

---

credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/components/specs/ShareProgramRecordModal.test.jsx
credentials/static/sass/views/_program-record.scss

[LEARNER-5895](https://openedx.atlassian.net/browse/LEARNER-5895)
The InputText field doesn't have an onCopy attribute, so I wrapped it in a div that does. That calls a function that checks what the highlighted text is (to make sure the full url was copied); if the full url was copied, it behaves the same way as if the copy to clipboard button was pressed (show alert and track event).
There doesn't appear to be a way to get a readonly mode with InputText field without disabling it, so I styled it to make it look "friendly".
Additionally, removed the horizontal padding on the url field.

Track users who manually copy link instead of clicking button

---

package-lock.json
package.json
webpack.config.js

Adds simple caching for webpack builds
**Before:**
real	1m12.901s
user	1m42.310s
sys	0m3.560s
 **After:**
real	0m39.541s
user	0m53.630s
sys	0m2.530s
~45% perf increase
Experimentally, Travis doesn't keep a persistent cache so it doesn't affect its builds.

Webpack Caching

---

credentials/settings/base.py

[LEARNER-6135](https://openedx.atlassian.net/browse/LEARNER-6135)
Django-hijack uses a follow through url that it always hits after masquerading, or releasing a user.  Since we reload the page to update the records view, users don't navigate to the follow through url, but it still has the potential to cause errors. Rerouting this to the admin page is safe, because all users, staff, and superusers will get a 200 from hitting either the admin dashboard or the admin login.  
**Sandbox**
Access the records page at https://credentials-masquerade-redirect.sandbox.edx.org/records/ .  
Users:
- Superuser: admin, admin@example.com
- Staff: credentials_service_user, no email
- User: verified, verified@example.com

Change masquerade redirect to the admin page

---

credentials/apps/core/tests/factories.py
credentials/apps/records/tests/test_utils.py
credentials/apps/records/utils.py
credentials/settings/base.py

[LEARNER-6099](https://openedx.atlassian.net/browse/LEARNER-6099)
**Sandbox**
---
Sandbox at https://credentials-masquerade-permissions.sandbox.edx.org/records/
Superusers: superuser, superuser2
Staff: staff
Users: verified
---
- UI Changes

Prevent superusers from masquerading as other superusers

---

credentials/apps/catalog/management/commands/copy_catalog.py

Previously the pathway deletion was occurring in fetch_pathways(), which was getting called for each site. This meant only the last site was getting its pathways stored.

Move pathway deletion to prevent multiple calls

---

credentials/apps/catalog/tests/test_commands.py
credentials/apps/catalog/tests/test_utils.py
credentials/apps/catalog/utils.py

[LEARNER-6144](https://openedx.atlassian.net/browse/LEARNER-6144)
Updates copy catalog job to temporarily send data to both Pathway & CreditPathway
---
- UI Changes

Update job to populate Pathway & CreditPathway

---

credentials/apps/catalog/management/commands/copy_catalog.py
credentials/apps/catalog/tests/test_commands.py
credentials/apps/catalog/tests/test_utils.py
credentials/apps/catalog/utils.py
credentials/apps/credentials/issuers.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/static/components/ProgramRecord.jsx
credentials/static/components/specs/ProgramRecord.test.jsx
docs/index.rst
docs/pathways.rst
docs/program_records.rst

Replace all backend usages of CreditPathway with Pathway in preparation for removing CreditPathway.
Currently does not change the language in the ProgramRecord or SendLearnerRecordModal files, since it was my understanding that those components will always be handling pathways that are associated with credit institutions.  Happy to rename if we decide we do want that updated.  Also, this PR does not include any updates to the dev docs, and I had a question about the updates that will go there.
---
- UI Changes

Start using Pathway model

---

credentials/apps/api/v2/filters.py
credentials/apps/api/v2/tests/test_views.py
credentials/apps/credentials/tests/test_utils.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/utils.py
credentials/apps/credentials/views.py
credentials/apps/records/management/commands/seed-records.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/templates/credentials/programs/base.html

Whenever we show a program credential, make sure that it is actually supposed to be shown. We rely on the visible_date field for program credentials to be actually populated by the LMS for this feature.
https://openedx.atlassian.net/browse/LEARNER-6263
---
- UI Changes

Filter program certs by visible_date

---

credentials/settings/base.py
requirements/base.txt

From edx-drf-extensions:
1. EnsureJWTAuthSettingsMiddleware: Ensures proper JWT auth settings
for endpoints.
2. JwtAuthCookieMiddleware: Combines the JWT auth cookie parts into a
JWT auth cookie.
ARCH-233
---
- UI Changes

ARCH-233: Add JWT Auth Middleware.

---

credentials/settings/base.py

When JWT cookies are required, there will be some work needed to make this work.  
See "[ARCH-266: Backend: Enable JWT Cookies in remaining IDAs.](https://openedx.atlassian.net/browse/ARCH-266)"

ARCH-262: Reverts addition of JwtAuthCookieMiddleware

---

credentials/apps/credentials_theme_openedx/static/sass/_layouts-rendering.scss
credentials/static/sass/_print.scss

While printing certificate it was adding blank page on chrome
browser. Also images were misaligned. To Fix these issues css
is modified in print media.
[LEARNER-6696](https://openedx.atlassian.net/browse/LEARNER-6696)

Fixed Program Certificate Issue while Printing

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

[LEARNER-7043](https://openedx.atlassian.net/browse/LEARNER-7043)
Learners enrolled in some programs i.e **Gestión Pública para el Desarrollo** are getting **_internal server error_**. The issue is in the filename. If the filename contains special characters that do not lie in ordinal range(128) of ascii it gives internal server error. The filename is created by following the pattern username_program_name_grades.csv. This filename becomes a part of Content Disposition and the error occurs in [gunicorn package](https://github.com/benoitc/gunicorn/blob/master/gunicorn/http/wsgi.py#L318) as it uses ascii
For a fix I changed the code to encode the file in 'utf-8' before sending it to response['Content-Disposition']
- I have setup gunicorn on local system and tested the changes
- Verified on …

LEARNER-7043: Encode filename to download record

---

credentials/apps/api/v2/permissions.py
credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/urls.py
credentials/apps/api/v2/views.py
credentials/settings/base.py

New API replaces all copies of username in this service with a new
username. Requires user be in a username_replacement_admin group. Should
only be ran as a larger job to update usernames across all services,
otherwise the system will be left in a broken state for those users.
---
- UI Changes

Add username replacement API

---

credentials/apps/api/accreditors.py
credentials/apps/api/tests/test_accreditors.py
credentials/apps/api/v2/serializers.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py

If for some site the Site Configurations for credentials have the option "Enable Learner Records" unchecked, the programs are not being saved into the database when management command copy_catalog is called. Hence send_updated_emails_for_program() should be called only if the site
configurations has the value for records_enabled set to true.
* Added another check to verify that config has records_enabled set to true before sending an updated email to a pathway org
[PROD-189](https://openedx.atlassian.net/browse/PROD-189)

PROD-189 send emails for program if records_enabled is true

---

credentials/apps/api/accreditors.py
credentials/apps/api/tests/test_accreditors.py
credentials/apps/api/v2/serializers.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py

---
This is a revert of https://github.com/edx/credentials/pull/643 because that didn't fix the prod issue we are seeing. This change uses the same mechanism to fix prod issue, but we are using the site config from the program cert instead of the request.

Use site configuration from program credential instead of the actual request site.

---

openedx.yaml

Also, remove `track-pulls`, which OEP-2 now says is an obsolete property.

Change repo owner from edx/learner to schenedx

---

requirements/base.txt

It looks like when new AMIs are built for this, they aren't necessarily build from scratch, and since any Django version under 2.0 will satisfy the pip requirement of "django<2.0", Django won't just get upgraded on build.  So I'm pinning an explicit version again.
- UI Changes

Pin django to 1.11.22

---

credentials/apps/api/accreditors.py
credentials/apps/api/tests/test_accreditors.py
credentials/apps/api/v2/serializers.py
credentials/apps/credentials/issuers.py
credentials/apps/records/tests/test_utils.py
credentials/apps/records/utils.py

Building the program record URL incorrectly by concatenating site domain and record path. Fixed by using request.build_absolute_uri().
PROD-564
---
- UI Changes

Fix program record url in credit request email.

---

credentials/apps/records/admin.py

**Ticket:** [Learner-6666](https://openedx.atlassian.net/browse/LEARNER-6666)
**Details:** 
Search field in admin view for program certificates returns 500 server error for all the inputs. 
https://credentials.edx.org/admin/records/programcertrecord/
**Solution:**
In the code, foriegn keys were being used instead of column names. 
Updated the correct column names for the search view.

ProgramCertRecord search view update in Admin Panel

---

credentials/apps/records/messages.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/utils.py
credentials/apps/records/views.py

previously we were using learner-records@edx.org in from address.
Now we will be using learner email address so that partner can
contact with learner.
Prod-624

Changed from_address while sending email to partner

---

credentials/apps/api/v2/filters.py
credentials/apps/api/v2/tests/test_views.py

[Learner-5999](https://openedx.atlassian.net/browse/LEARNER-5999)
**Problem**
Giving invalid uuid in credentials api raises a validation exception.
**Solution**
Added an except clause to return an empty list in case of invalid UUID instead of raising an exception.
Test checks if invalid UUID returns an empty list instead of raising validation error or not.

Invalid UUID error in credentials api view

---

docker-compose.yml

[PROD-830]
This is being added to deal with a failure in tests running with the
current version.
---
- UI Changes

Restriction on the version of MySql that we use for testing

---

credentials/apps/catalog/models.py

This is the 4.1th stage of renaming the start and end fields of
CourseRun to start_date and end_date.
This release ONLY removes the django model fields corresponding to the
old columns.  Note that this does not include the migration to remove
the columns.
DE-1708
Testing in devstack
---
To test, I added a "dummy" column into the middle of the core_user table:
```
mysql> ALTER TABLE core_user ADD COLUMN dummy varchar(255) NULL AFTER username;
Query OK, 0 rows affected (0.09 sec)
Records: 0  Duplicates: 0  Warnings: 0
mysql> describe core_user;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | int(11)      | NO …
```

Rename start and end fields (4.1/4)

---

credentials/settings/base.py
requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

- Upgrade edx-drf-extensions to 2.4.5
- Remove unused JWT_AUTH_REFRESH_COOKIE setting.
ARCH-418, ARCH-1269, ARCH-1044
---
- UI Changes

ARCH-1269: upgrade edx-drf-extensions to 2.4.5

---

credentials/static/components/ProgramRecord.jsx

Credentials service is not rounding the user grade in a particular course while displaying it on the learner record.This makes an inconsistent behaviour compared to support tool as well as progress
page.To fix it, learner grade are rounded properly so that a consistent grade would appear on all views.

Grades on learner record are not consistent with progress page.

---

requirements/pip_tools.txt

It seems like there was a pip/piptools version incompatibility which
was preventing make upgrade from even getting started
---

Address an issue that was preventing make upgrade

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Upgrading requirements to bump credentials theme to install the new
MicroBachelors programs cert templates.
---
- UI Changes

Update credentials themes to include MB certs

---

credentials/apps/records/views.py
credentials/settings/base.py
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt

Relevant JIRA issue can be found [here](https://openedx.atlassian.net/browse/BOM-1259).
This PR also contains changes for `edx-auth-backends` (JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1266)) upgrade.

Upgrade django-ratelimit BOM-1259

---

credentials/apps/api/authentication.py
credentials/apps/api/tests/test_authentication.py
credentials/settings/base.py

According to our investigation using new relic custom metrics, BearerAuthentication class is not used and is safe for removal.
[PR that adds metric](https://github.com/edx/edx-drf-extensions/pull/105)

Removing use of BearerAuthentication

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

`edx-ace` was pinned [here](https://github.com/edx/credentials/pull/754/commits/86c7ec1a167a2776f9da29719fb69b4b68e4548a) by @dianakhuang because installing `edx-ace` alongside an older version of `attrs` broke tests.
This happened because I didn't realize that [my `edx-ace` change](https://github.com/edx/edx-ace/commit/6b203f7280d038447328094649b58862f0abe794) wasn't compatible with older versions of `attrs`, and didn't add a constraint to its `setup.py`.
I don't think pinning `attrs` to an old version for credentials was necessary in the first place, so this PR unpins it so that we can install the newest version of `edx-ace`.
@schenedx Please review when you have a chance.

Allow edx-ace to be upgraded by unpinning attrs

---

Makefile
db_keyword_overrides.yml

I have enabled the reserved keyword linter to run for all of the default database systems (MYSQL, SNOWFLAKE, STITCH). This entailed adding any current keyword violations to the override file as to not fail CI.
---
- UI Changes

run linter on all systems

---

credentials/settings/production.py
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.txt

Please see https://openedx.atlassian.net/browse/EDUCATOR-4716
Most of the upgrades are to patch/minor versions, which I'm not worried about.
`pyyaml` was upgraded two major versions, but I'm familiar with the change-set and I feel comfortable with this upgrade.
`pillow` I am not familiar with, and it's been upgraded by three major versions. This is the one dependency upgrade that I'm not confident about.
@edx/masters-devs

Address EDUCATOR-4716: Backend

---

credentials/settings/devstack.py

Imported the `private.py` file into `devstack.py` so that user using devstack can easily change their variables using `private.py`. Previously `private.py` was imported in `local.py` but `local.py` is not getting used anywhere so if user put anything into `private.py` it will not reflect in the settings.

Import `private.py` into `devstack.py` 

---

package-lock.json
package.json

Re: [MST-124](https://openedx.atlassian.net/browse/MST-124?atlOrigin=eyJpIjoiN2UzYjAzY2I4NWUyNGRhMDlkOTQ0N2I2NjYyNDdmZDciLCJwIjoiaiJ9)
node-sass 4.9.3 does not support Node v12 and breaks the build process. Tested and updated to 4.14.1 in order to safely merge https://github.com/edx/configuration/pull/5470

Update node-sass to support Node v12

---

credentials/apps/core/views.py

---
`render_to_response` is removed in Django 3 ([ref](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-removed-in-3-0)), this PR will replace `render_to_response` usage with `render`.
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1881)
- UI Changes

Replaced deprecated method usage

---

credentials/apps/records/views.py

---
https://openedx.atlassian.net/browse/MST-316
Adding the "url" property to GA events as part of the missing info needed on segment events.
@edx/masters-devs-cosmonauts and @brianhw Please review

MST-316 Add the page full URL to GA events

---

credentials/apps/catalog/tests/factories.py
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.txt

Updated pinned versions to fix failed python upgrade job:
- `mock` and `zipp` pinned due to `Python>=3.6` requirement
- `requests` unpinned as it no longer causes an upgrade issue
Fixed [bad import alias removed](https://factoryboy.readthedocs.io/en/latest/changelog.html#id2) in `factory-boy==3.x`

Python Requirements Update

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

superuser
[MICROBA-598]
The Credentials endpoint program-listing/ was meant for the support
team and internal teams to use as a debugging tool. The user type
Superuser was improperly used and now that less internal users
have that role it is unusable. Changing this to the Django Staff role
will allow internal users to access the tool again.
---
- UI Changes

Update the Credentials program-listing endpoint to use Staff instead of

---

credentials/settings/devstack.py

[MICROBA-521]
- Update default JWT auth settings for development in Credentials with latest from cookiecutter IDA settings

MICROBA-521 | Fix default JWT issuer for development

---

credentials/apps/records/management/commands/seed-records.py

Use class to fix faker warning reported in travis build.
https://travis-ci.org/github/edx/credentials/jobs/732347131
> Traceback (most recent call last):
>   File "./manage.py", line 15, in <module>
>     execute_from_command_line(sys.argv)
>   File "/edx/app/credentials/venvs/credentials/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/edx/app/credentials/venvs/credentials/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/edx/app/credentials/venvs/credentials/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
> …

Use class to fix faker warning

---

acceptance_tests/runtests.sh
credentials/apps/records/management/commands/seed-records.py

The acceptance tests were catching the exit code and always returning
zero indicating success even if they weren't passing.
Disabled a11y tests since they would have been failing for a long time now. Will put in a ticket to fix them and reenable them.

Fix always passing acceptance tests

---

requirements/constraints.txt

importlib-metadata is breaking in `make upgrade`. Pinning the
version until the upstream fixes are released.
Note: verifed that `make upgrade` works locally, but going to let the job do the upgrade.

Fix upgrades by pinning library

---

acceptance_tests/runtests.sh
credentials/static/sass/_base.scss
credentials/static/sass/views/certificate.scss
credentials/templates/credentials/base.html

The goal of this PR is to fix the existing test failures and re-enable the accessibility tests.
In a future ticket, we'll come back and upgrade dependencies. See [MICROBA-653](https://openedx.atlassian.net/browse/MICROBA-653).
Original text color:
Proposed text color:

MICROBA-625 Fix accessibility tests

---

requirements/constraints.txt
requirements/production.in

Remove _boto_ and unpin _django-storages_ (since we no longer need _boto_). Also unpin _importlib-metadata_ since that upgrade problem should be fixed.

MICROBA-628 Remove boto and unpin django-storages

---

credentials/urls.py
credentials/views.py

As part of Architecture's observability work, we're adding endpoints to IDAs that can dump the current state of various toggles.  This is a mock endpoint that accomplishes two things: 1) confirm that we can require a staff JWT in another IDA than edxapp, and 2) allow us to test integration of multiple IDAs into toggle state reports before the edx-toggles djangoapp is ready for use.
This can go away once edx-toggles is ready and integrated.
You can test locally in devstack: http://localhost:18150/mock-toggles

ARCHBOM-1569: Add a mock toggles state endpoint

---

requirements/base.in
requirements/constraints.txt
requirements/test.in

1. Add code-annotations dependency. 
2. Unpin stevedore (we need a later version for code-annotations to work). 
3. Update comments and alphabetize.

MICROBA-634 Add code-annotations dependency

---

credentials/static/js/sharing.js
credentials/static/js/test/specs/sharing_spec.js

[EDUCATOR-5400](https://openedx.atlassian.net/browse/EDUCATOR-5400)
We've seen several newrelic alerts for the past few days that are caused by this error with facebook integration.
Simple change to prevent these errors from popping up when the facebook badge isn't present (it's currently never present)

EDUCATOR-5400: gracefully handle the facebook button not existing

---

karma.conf.js

Fixes warning in django builds: _WARN [watcher]: Pattern "/edx/app/credentials/credentials/credentials/static/components/**/*.js" does not match any file_

MICROBA-639 Remove file path with no entries

---

credentials/static/components/SendLearnerRecordModal.jsx
credentials/static/components/specs/SendLearnerRecordModal.test.jsx

Fixes build warnings
console.error
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Modal`. It was passed a child from SendLearnerRecordModal. See https://fb.me/react-warning-keys for more information.
in withDeprecatedProps(Button) (created by SendLearnerRecordModal)
in Modal (created by SendLearnerRecordModal)
in SendLearnerRecordModal (created by ProgramRecord)
in main (created by ProgramRecord)
in ProgramRecord (created by WrapperComponent)
in WrapperComponent
and
console.error
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `SendLearnerRecordModal`. See https://fb.me/react-warning-keys for more information.
in withDeprecatedProps(asInput) (created by SendLearnerRecordModal)
in SendLearnerRecordModal …

MICROBA-639 Add key

---

.github/workflows/ci.yml
Makefile
credentials/apps/catalog/tests/factories.py
docker-compose.travis.yml
docker-compose.yml

This is v1 to unblock credentials. Cleanup will happen later.

Add Github Action CI tests

---

credentials/apps/catalog/api.py
credentials/apps/catalog/data.py
credentials/apps/catalog/tests/test_api.py
credentials/apps/credentials/exceptions.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_models.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py

Instead of relying on cached calls to the discovery API, this uses the
in-service catalog to support program_details which certificates use.
Also removed subtitle since no code is actively using it.

Switch program_details to use in service catalog [MICROBA-726]

---

credentials/apps/credentials/utils.py
credentials/templates/credentials/edx_ace/common/base_body.html
credentials/templates/credentials/edx_ace/programcertificateissuedmessage/email/head.html

[MICROBA-737](https://openedx.atlassian.net/browse/MICROBA-737)
Addresses all stickies (red and orange) shown here:

MICROBA-737 Rebrand program completion email

---

credentials/apps/api/v2/views.py

My decision for disabling it entirely for staff is that the 1500 req/min is useless. If we ever got to 1500 req/min, the caching of the ratelimiting would actually kill us before the users requests would have a chance to get there.

Don't throttle staff accounts

---

credentials/apps/api/urls.py
credentials/apps/api/v2/urls.py
credentials/apps/credentials/urls.py
credentials/apps/edx_django_extensions/urls.py
credentials/apps/records/urls.py
credentials/urls.py

Fixes
> credentials/apps/api/v2/urls.py:8
>   /edx/app/credentials/credentials/credentials/apps/api/v2/urls.py:8: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
>     url(r'^replace_usernames/$', views.UsernameReplacementView.as_view(), name="replace_usernames")
>

MICROBA-639 Replace url with re_path

---

credentials/apps/core/forms.py
credentials/apps/credentials/views.py
credentials/apps/edx_django_extensions/views.py
credentials/apps/records/views.py

Fixes
> credentials/apps/core/tests/test_forms.py::SiteConfigurationAdminFormTests::test_clean_with_invalid_facebook_config_1_
> credentials/apps/core/tests/test_forms.py::SiteConfigurationAdminFormTests::test_clean_with_invalid_facebook_config_2_None
>   /edx/app/credentials/credentials/credentials/apps/core/forms.py:12: RemovedInDjango40Warning: django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext().
>     message = _('A Facebook app ID is required to enable Facebook sharing.')
>

MICROBA-639 Replace ugettext with gettext

---

credentials/apps/catalog/tests/test_utils.py
credentials/apps/records/management/commands/seed-records.py
credentials/settings/base.py
jest-config.json

Fixes:
> 
> /edx/app/credentials/venvs/credentials/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1424: RuntimeWarning: DateTimeField CourseRun.end_date received a naive datetime (2018-06-01 00:00:00) while time zone support is active.
>   warnings.warn("DateTimeField %s received a naive datetime (%s)"
and
> edx-credentials@ test-react /edx/app/credentials/credentials
> > jest --no-cache --coverage  --config ./jest-config.json
> 
> jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
>   Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
>   Error: Watchman error: A non-recoverable condition has triggered.  Watchman needs your help! …

MICROBA-639 Fix warnings

---

credentials/apps/core/admin.py
credentials/apps/core/models.py
credentials/apps/credentials/forms.py
credentials/apps/credentials/models.py
credentials/apps/records/models.py
credentials/urls.py

Fixes
> credentials/apps/core/models.py:24
>   /edx/app/credentials/credentials/credentials/apps/core/models.py:24: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
>     verbose_name=_('Platform Name'),
>

MICROBA-639 Replace ugettext_lazy with gettext_lazy

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt

The bug mentioned on [ARCHBOM-1078](https://openedx.atlassian.net/browse/ARCHBOM-1078) is fixed in `social-auth-core==3.3.3`, See [this comment](https://openedx.atlassian.net/browse/BOM-2094?focusedCommentId=514498) for details, now we are unpinning it wherever it was previously pinned due to that bug.
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2183

BOM-2183 : Unpin social-auth-core

---

package-lock.json
package.json

Update babel-jest for security. Considering jest is a testing library and none of our tests failed, I'm gonna say this is a safe upgrade.

Update babel-jest dependancy

---

package-lock.json
package.json

[MICROBA-909](https://openedx.atlassian.net/browse/MICROBA-909)
Upgrading from `0.5.9` -> `4.1.1`!
Changelog here: https://github.com/webpack-contrib/url-loader/blob/master/CHANGELOG.md
- Breaking changes:
- `1.0.0`:
- Sets `engines` to `"node": ">= 6.9.0 || >= 8.9.0"`
- Drops support for `webpack =< v2.0.0`
- `2.0.0`:
- minimum required nodejs version is `8.9.0`
- `limit` should always be a number and 0 value handles as number
- fallback loader will be used than limit is equal or greater (before only when greater)
- `3.0.0`
- minimum required nodejs version is `10.13.0`
- rename the `esModules` option to `esModule`
- switch to ES modules by default (the option `esModule` is `true` by default)
- `4.0.0`
- deps: migrate on mime-types package, some rare types may have other mimetype …

MICROBA-909 Upgrade url-loader

---

Makefile

Create node_modules volume instead of bind mounting local folder. Bind
mounting doesn't work because node-sass has environment bindings.

Fix node_modules Mac issues

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py

Add some logging when attempting to issue a credential so that we have a better idea as to what learner is affected should an issue arise.

Add logging when issuing credentials

---

credentials/apps/credentials/views.py

[MICROBA-994](https://openedx.atlassian.net/browse/MICROBA-994)
You can read more about lazy translation here: https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#lazy-translation
**The problem**
One particular string on program certificates configured to use Spanish is not being translated into Spanish.
**The solution**
That particular string is constructed in the view rather than the template. It was getting translated before/without knowing what language is set from the program certificate configuration. Using this "lazy translation" tells this string to wait to be translated until actually used in the template, at which point it knows about which language it’s supposed to use from the configuration.

MICROBA-994 Use gettext_lazy to defer translation until used in template

---

renovate.json

The _dependencyDashboard_ setting creates an issue with an overview dashboard. Since credentials doesn't use issues (we track things in jira), it didn't seem to have any effect. I'm suggesting we remove it for simplicity.
Doc: https://docs.renovatebot.com/configuration-options/#dependencydashboard

Remove dependencyDashboard since credentials doesn't use issues

---

requirements/constraints.txt

Version 1.0.0 is not released yet. This is just in advance.
Fixing https://openedx.atlassian.net/browse/MICROBA-649 should let us unpin it.

Pin edx-ace to a version that won't break us

---

acceptance_tests/pages.py
credentials/apps/api/v2/views.py
credentials/apps/catalog/management/commands/copy_catalog.py
credentials/apps/catalog/tests/test_commands.py
credentials/apps/catalog/utils.py

The copy_catalog management command now had optional deletions if you pass the `--delete` flag. This will propogate Discovery deletions into Credentials.
This does **not** currently do any checks on related models. It simply deletes the object or doesn't (depending on the `--delete` flag). The only `CASCADE` we have currently is that a CourseRun will be deleted if we delete the related Course.

Add deletions to copy_catalog command

---

credentials/apps/credentials/management/commands/create_program_certificate_configuration.py
credentials/apps/credentials/management/commands/tests/test_create_program_certificate_configuration.py

feat: Add command to create program cert config
This adds a command to create a program certificate configuration for the demo program. This command is meant to be used by a provisioning script, and not ran by hand. This command will not work unless the demo program is in the catalog.

MB-849: Improve credentials usability in devstack

---

credentials/apps/catalog/tests/test_utils.py
credentials/apps/catalog/utils.py

Not all course runs were being returned on the courses API. We have to add this extra parameter to get them.

fix: Request hidden course runs

---

credentials/apps/core/models.py
credentials/apps/core/tests/test_models.py
credentials/apps/credentials/forms.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_forms.py
credentials/apps/credentials/tests/test_models.py

Only changes credentials internals to use catalog data instead of
contacting discovery directly. Remove the get_program method and changes
all downstream consumers to use the catalog program instead.

refactor: Remove get_program and it's callers

---

credentials/apps/catalog/management/commands/copy_catalog.py
credentials/apps/catalog/utils.py

Fixes some logging as well. Failing when there's deletions to be done
without a --delete flag lets the developer know to verify the deletions
before running again with --delete.

feat: Make copy_catalog fail if there's deletions

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Unpin edx-auth-backends and run _make upgrade_.
I think the auth issue we were seeing was fixed a while back: https://github.com/edx/auth-backends/pull/97
This also removes the _docker-compose_ pin, as it doesn't seem to be needed (and other repos don't have anything similar).

Unpin edx-auth-backends

---

credentials/apps/api/v2/serializers.py
credentials/apps/api/v2/tests/test_serializers.py
credentials/apps/api/v2/urls.py
credentials/apps/api/v2/views.py

This PR will create an API to expose the course certificate configuration so that the LMS can talk directly with Credentials and explicitly add the certificate availability date to a certificate configuration.
Previously, we were running into an issue where the LMS would send over a "visible date" that would be one of a few values; possibly the availability date, possibly the created date, modified date, etc. In order to reduce confusion and prevent bugs, we plan to add the availability date explicitly on any configuration that has one.

[feat] MB-1167 Certificate Availability API

---

credentials/settings/base.py
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

This work adds a temporary WaffleSwitch to gate the use of the
certificate_available_date field on the CourseCertificate model while
we develop features around it.
This ONLY adds the switch, but doesn’t use it yet.
To use the toggle:
1. In the waffle section of the django admin
(< credentials host >admin/waffle/), add a new Switch with the name:
`credentials.use_certificate_available_date`. Make sure it is
"active".
2. In the code, call the switch like this:
```
from credentials.settings.base import USE_CERTIFICATE_AVAILABLE_DATE
if USE_CERTIFICATE_AVAILABLE_DATE.is_enabled():
```
Original ticket: https://openedx.atlassian.net/browse/MICROBA-1169
Ticket to remove flag: https://openedx.atlassian.net/browse/MICROBA-1198

feat: add toggle for certificate_available_date

---

credentials/apps/api/v2/serializers.py
credentials/apps/api/v2/tests/test_serializers.py
credentials/apps/api/v2/views.py

[fix] Add permisssions and fix CourseCertificateSerializer
The CourseCertificateSerializer needed permission for the LMS
credentials_service_worker to operate properly. I opted for the admin
user permission instead of writing its own, because the worker should be
the only one making changes with this API anyway.
I've also reworked the serializers create() function to fix it. The
update portion of update_or_create() was not properly working because of
the unique together constraint on the model. Some of the tests were
modified to reflect the change made to create().

MB-1167: CourseCertificateSerializer Fix

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/credentials/tests/factories.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/utils.py
credentials/apps/records/tests/test_views.py

This commit updates / adds some utility methods to use our new
certificate_available_date field on CourseCertificate (instead of the
visible_date on UserCredentialAttribute) for any methods that need
to filter certs to show only those that should be visible (i.e., whose
certificate_availbable_date is not in the future).
The filter_visible method (altered here) is used in the following
places:
- get_record_data: a method called by ProgramRecordView and
ProgramRecordCsvView. It provides all the record data for a given
user and program--but only the visible course and program
certificates
- RecordsListBaseView: gets all the credentials for a given user,
sorted by program or course certificate type—-but only wants
the visible ones.
- handle_only_visible: through the UserCredentialFilter. This …

feat: use certificate_available_date field for filters

---

credentials/apps/credentials/constants.py
credentials/apps/credentials/models.py

While trying to update the available_date for CourseCertificates in
credentials, we were getting errors that master's program course
certificates were not being properly updated. this add's Masters to the
list of valid CourseCertificate configurations.

[feat] Credentials masters CourseCertificate support

---

requirements/constraints.txt

Add temporary pin for _edx-drf-extensions_ to unblock make upgrade
edx-drf-extensions' recent change to use **pyjwt[crypto]==2.1.0** seems to be in conflict with the common constraint pin of **pyjwt[crypto]==1.7.1** and results in this error when trying to upgrade credentials:
> # The following packages are considered to be unsafe in a requirements file:
> # pip
> # setuptools
> pip-compile --rebuild --upgrade -o requirements/base.txt requirements/base.in
> Could not find a version that matches pyjwt[crypto]==1.7.1,>=2.1.0 (from -c https://raw.githubusercontent.com/edx/edx-lint/master/edx_lint/files/common_constraints.txt (line 22))
> Tried: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.3, 0.2.3, 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.3.2, 0.3.2, 0.4.0, 0.4.0, …

chore: Add temporary pin for edx-drf-extensions to unblock make upgrade

---

requirements/constraints.txt

Remove _edx-drf-extensions_ pin as this has been moved to the common-constraints file
https://github.com/edx/edx-lint/blob/master/edx_lint/files/common_constraints.txt
MICROBA-1435

fix: Remove edx-drf-extensions pin

---

acceptance_tests/test_records.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/settings/base.py
credentials/settings/devstack.py
credentials/static/components/ProgramRecord.jsx
credentials/static/components/ProgramRecordFactory.jsx
credentials/templates/programs.html

[MICROBA-1441]
* Introduces two new settings -- `USE_LEARNER_RECORD_MFE` and `LEARNER_RECORD_MFE_RECORDS_PAGE_URL`.
* Updates existing React components in Credentials to use Learner Record MFE setting (if needed).
We needed a way to navigate back to the Learner Record MFE from the program detail page(s) for a learner. Otherwise, we will end up going back to the legacy experience (the link is hard-coded to go to `/records/ page).

fix: enable navigation from program detail page to Learner Record MFE (if needed)

---

.github/workflows/push-docker-image.yml
Dockerfile
credentials/docker_gunicorn_configuration.py

This image builds on our existing (non-ansible) Dockerfiles with the
following exceptions:
- It's the first to require node to build static assets. I've followed
the pattern we use in the ansible builds where we use nodeenv and I've
also taken the node and npm versions from ansible. This pattern may
change in the future but for now I'm prioritizing consistency with the
existing images.
- This is also the first one being used in devstack, so to utilize
existing devstack code, the folder structure has to have an additional
layer. The repo folder will live at /edx/app/credentials/credentials
instead of the /edx/app/<service> that other's use.
I tested this by building the image locally and pointing my devstack at it.

feat: Add dockerfile and push image to Dockerhub

---

.github/workflows/upgrade-python-requirements.yml

Success notification allows us to autoclose alerts once they're fixed.

Add success notificate to upgrade job

---

README.rst

Frontend development requires additional commands to work out of the box. This adds those to the README.

docs: Add frontend bundling to README

---

credentials/apps/credentials/tests/factories.py
credentials/apps/credentials/utils.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

When displaying the Program Record, use the date override (if present)
for the date value in the "Date Earned" column. This will make the
Program Record match the date displayed on the learner’s course
certificate.
**This will only display properly if the `USE_CERTIFICATE_AVAILABLE_DATE` waffle switch is enabled.** No, these changes are not related to that feature, but take my choice to leave this out of the old code paths as a bet that we’ll move forward and clean up that old code.

feat: Use date override on Program Record

---

credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/utils.py
credentials/apps/records/tests/test_views.py

This PR fixes an issue where the Program certificate would show an
incorrect issue date based on when a course cert was created in
Credentials rather than when it was issued from the LMS.

fix: corrects issue with issue_date and visible_date

---

credentials/settings/base.py

**Issue:** [BOM-2782](https://openedx.atlassian.net/browse/BOM-2782)
- Added the `DeploymentMonitroringMiddleware` to record `Django` and `Python` versions in the `NewRelic`.

BOM-2782: Use Deployment Monitoring Middleware in settings

---

requirements/constraints.txt

Temporarily pins `pyyaml` to versions < 6.0. The upgrade job started failing after `pyyaml` 6.x was released because `docker-compose` is looking for versions <6.0, >=3.10.
This pin will be re-evaluated and removed as part of MICROBA-1556.

chore: pin pyyaml version to fix upgrade job

---

credentials/apps/core/tests/test_models.py

The VERIFIED_NAME_FLAG was added as part https://github.com/edx/edx-name-affirmation/pull/12, [MST-801](https://openedx.atlassian.net/browse/MST-801) in order to control the release of the Verified Name project. It was used for a phased roll out by percentage of users.
The release reached a percentage of 50% before it was observed that, due to the way percentage roll out works in django-waffle, the code to create or update VerifiedName records was not working properly. The code was written such that any change to a SoftwareSecurePhotoVerification model instance sent a signal, which was received and handled by the Name Affirmation application. If the VERIFIED_NAME_FLAG was on for the requesting user, a Celery task was launched from the Name Affirmation application to perform the creation …

feat: Remove Use of Verified Name Enabled Flag

---

.github/workflows/push-docker-image.yml
Dockerfile

build: tweak dockerfile; build and push both base and dev images
dockerfile changes:
* rename stages ('app', 'devstack') to ('base', 'dev')
to match edx-platform's Dockerfile.
* add comment to top of dockerfile warnings of its experimental
dev-only state.
* remove newrelic build stage, which doesn't belong in the
core openedx repository.
* touch ../credentials_env for devstack compatibility.
See the testing instructions for the [devstack PR](https://github.com/edx/devstack/pull/866).
This is a dependency attempt to [use the experimental images in devstack](https://github.com/edx/devstack/pull/866), which itself is part of the effort to [move off of edxops DockerHub org images](https://github.com/edx/devstack/issues/869).

build: tweak dockerfile; build and push both base and dev images

---

.github/workflows/push-docker-image.yml

@Tj-Tracy do you mind reviewing this too? My [last PR](https://github.com/edx/credentials/pull/1510) had a bug in the GitHub action.
I hope it works... I wish I knew a way to test these workflows locally!

build: fix get-tag-name in docker push workflow

---

requirements/pip_tools.txt

Manually update the `pip-tools.txt` generated file to fix an issue with
pip and pip-tools. `pip 22.x` and `pip-tools <6.5` are not compatible with
each other. Normally, we shouldn't modify a generated file but we are
stuck without doing it this time.

fix: manually update pip-tools to unbreak workflow

---

.github/workflows/upgrade-python-requirements.yml

* Adjusts the cron schedule of the `upgrade-python-requirements` job to run on Mondays.

chore: adjust `upgrade requirements` job to run on Monday

---

.github/workflows/ci.yml

BREAKING CHANGE: Dropped Node 12 support

chore!: Dropped support for Node 12

---

credentials/static/components/SendLearnerRecordModal.jsx
credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/components/specs/ShareProgramRecordModal.test.jsx

[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102#)
Updated deprecated `Checkbox` to `Form.Checkbox` and `InputText` to `Form.Control`.

Paragon form component deprecations

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

This PR refactors a REST API endpoint that creates a `ProgramCertRecord` and returns the URL for that public record. Currently, that URL is routing to the legacy frontend. With this refactor, if the Learner Record MFE is enabled, it will instead return the URL for the MFE.

refactor: REST API to return a different response if LR MFE is enabled

---

credentials/apps/records/rest_api/v1/permissions.py
credentials/apps/records/rest_api/v1/tests/test_views.py
credentials/apps/records/rest_api/v1/views.py

This is a PR to modify the existing REST API endpoints used by the LR MFE. This modification adds a `username` query param that is employed the the Support Tools MFE to fetch the same data learners see. 
Custom permissions classes were necessary here to block access from unauthorized users. We needed to ensure that learners (or other non-staff, non-superusers) couldn't view the records of others.
[Here is a truth table](https://docs.google.com/spreadsheets/d/1kNZ1Ff0jz_-cQ00yyZrpII95R7565QuRVeghEAppfI0/edit#gid=0) that attempts to illustrate how access is handled with the addition of this query parameter.

refactor: modify REST API endpoints for LR MFE

---

docs/decisions/0005-program-id-in-usercreditpathway.rst

feat: Explain the decision to extend UserCreditPathway to include the associated Program.
This will solve issues with ambiguity for learners who complete a pathway but can only get credit for one program associated with the pathway.

docs: add ADR for adding program_id to UserCreditPathway

---

credentials/apps/api/v2/serializers.py

In PR #1763, Django Rest Framework made a breaking change in a minor version release of their package. When attempting to fix this issue, I noticed some logic that was changing/updating data before validation in an overridden `is_valid` function. I made this change based on some reading I had done suggesting that this kind of data modification should be done in a dedicated Serializer Field class or by overriding the `to_internal_value` function in the Serializer class.
After making this change we were alerted to a number of errors occurring in the Credentials service. It looks like the data dict I was attempting to modify is immutable and can't be changed. Thus, I need to go back to the original implementation.

fix: revert recent change to CourseGradeSerializer

---

Dockerfile
configuration_files/credentials.conf
configuration_files/credentials.yml
configuration_files/supervisor.conf
configuration_files/supervisorctl
credentials_gunicorn.py
scripts/credentials.sh
scripts/devstack.sh

**ISSUE:** https://github.com/openedx/devstack/issues/962
This PR is part of effort aimed at removing Ansible based configurations and replacing them with Dockerfile. Currently Devstack Docker images are built using Ansible based configurations in the configurations repository. Through this effort we will make sure that the Repo has its own Dockerfile which has all the necessary configurations to setup small production and dev environments.
**Steps to run this Image with Devstack:**
- Build the Image locally first using the target `dev` i.e. `docker build -t image-name-of-choice --target dev .`
- After the image is built successfully go to the `docker compose` file of `devstack` and replace the existing `registrar` image with the one that you built without changing any other …

Convert ansible to dockerfile

---

credentials/apps/records/api.py
credentials/apps/records/tests/test_api.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/urls.py
credentials/apps/records/views.py

[APER-1975]
It is possible for learners to generate a link to a public version of their program record(s) to allow external entities to view their progress. This is particularly important as we embed these links within messages that get shared via credit pathways. We wanted to ensure that these links are not broken when the default experience becomes the Learner Record MFE, so we will be redirecting requests to the legacy view to the Learner Record MFE.
* Implement a redirect when a public program record is being requested (and the Learner Record MFE is enabled)
* Implement a redirect when hitting the records index page (and the Learner Record MFE is enabled)
* Fix an issue with the shared program record UUID being returned with dashes (Credentials can't process UUIDs with dashes in the …

feat: redirect users to LR MFE records pages where appropriate

---

credentials/static/components/Analytics.jsx
credentials/static/components/FoldingTable.jsx
credentials/static/components/MasqueradeBanner.jsx
credentials/static/components/MasqueradeBannerFactory.jsx
credentials/static/components/ProgramIcon.jsx
credentials/static/components/ProgramRecord.jsx
credentials/static/components/ProgramRecordFactory.jsx
credentials/static/components/RecordsFactory.jsx
credentials/static/components/RecordsHelp.jsx
credentials/static/components/RecordsList.jsx
credentials/static/components/SendLearnerRecordModal.jsx
credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/sass/_layouts.scss
credentials/templates/_masquerade.html
credentials/templates/programs.html
credentials/templates/records.html

[APER-1975]
After releasing the Learner Record MFE we plan on starting removal of the legacy frontend components within the Credentials IDA. This PR just adds comments to the more obvious things which are clear for removal.

docs: Add comments on legacy frontend components/classes that can be removed as part of issue #1722

---

.github/workflows/upgrade-python-requirements.yml

The edx-aperture team doesn't seem to exist anymore. I believe it may have been renamed to 2U-aperture which would explain the reason the automation can't add the correct reviewers.

fix: fix team tagging issue causing the Python upgrade automation to throw an error

---

credentials/apps/core/views.py
credentials/apps/credentials/templatetags/i18n_assets.py

When a template can't be found, there are no logs indicating the actual resource that was being accessed.
Added error logging for missing templates.

chore: add error logging to select_template calls

---

credentials/apps/records/api.py
credentials/apps/records/tests/test_api.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/urls.py
credentials/apps/records/views.py

[APER-1975]
This change backports recent changes to the Credentials IDA supporting the Learner Record and Support Tools MFEs. The following changes have been cherry picked from the main branch:
- feat: redirect users to LR MFE records pages where appropriate (cherry picked from commit ecf6463d303e268d1fc251c37716719d524a48e6)

chore: backport learner record redirection changes to Olive

---

requirements/constraints.txt

Pins the `django-ratelimit` package to versions < 4.x as it introduced a breaking change. This will be re-evaluated and removed as part of APER-2169.

fix: pin django-ratelimit to versions < 4.x

---

docs/decisions/0006-plugin-extensions.rst

In this ADR you will find a proposal to adopt plugin extensions system, initially implemented in the Open edX platform, but latter was extracted from it and now is ready for using by IDAs, ref. https://github.com/openedx/edx-django-utils/blob/master/docs/decisions/0002-extract-plugins-infrastructure-from-edx-platform.rst.
This ADR is proposed as a part of [FC-0002](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3493822533/General+Design+for+Sharing+Open+edX+Credentials+-+FC-0002) General Design for Sharing Open edX Credentials
Ticket: https://github.com/openedx/credentials/issues/1735

docs: [FC-0002] plugin extensions ADR

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile

This adds a new Makefile target that will install Firefox and run the tests using Karma. There is also a PR template that will remind future contributors to run these tests locally. Once a fix is found for getting these tests to run in CI, we will need to remove this PR template.

fix: added Makefile target to run tests with Karma

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

Fix the download records functionality when Segment is not used.
The user is getting the error if the platform has no Segment settings.
**Preconditions**
- The `segment_key` setting in the credentials site configurations is empty
**STR**
1. Go to the records page, click "Share" and copy the sharing URL:
2. Open the copied URL in the new tab or incognito window and click "Download":
**Actual Result**
User see the 500 error:
Error logs:
```
Traceback (most recent call last):
File "/edx/app/credentials/venvs/credentials/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/edx/app/credentials/venvs/credentials/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = …
```

fix: download records without Segment setup

---

Dockerfile
credentials/settings/utils.py

Working on this ticket https://2u-internal.atlassian.net/browse/PSRE-2079 we are moving credentials app to k8s.
First, we have enabled the stage credentials app on the stage EKS cluster and the app is throwing errors as `webpack-stats.json` is missing from the app directory, so adding instructions in Dockerfile to install npm dependencies and run webpack during the docker build.

fix: install npm and run webpack inside Dockerfile (PSRE-2079)

---

credentials/templates/programs.html

**Description:**
This PR is necessary in order to fix the bug when going to page /records/programs/#UUIDprogram (). Added a quote to the JS script for correct display of the Program Record page.
Program records page crashes because of the error in the [JS script](https://github.com/openedx/credentials/blob/open-release/nutmeg.master/credentials/templates/programs.html#L39) syntax - missing the closing ' symbol. 
**Note:** the issue is also has been already fixed in [master](https://github.com/openedx/credentials/blob/master/credentials/templates/programs.html#L40)
[@DmytroAlipov](https://github.com/DmytroAlipov) is covered by the RaccoonGang CLA

fix: program records are absent for nutmeg

---

.github/workflows/add-to-project.yml

The openedx org has a shared action to add items to projects. Use it to manage the credentials project.

build: use the shared action to add new items to project 23

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

[APER-2224]
Credentials already handles redirects for requests to the records page (credentials.blah.whatever/records) and shared program records (credentials.blah.whatever/programs/shared/{shared_program_record_UUID}/. Early in the implementation of the Learner Record MFE, we put logic in the LMS to build a URI directly to the _private_ program record pages in the LR MFE. This has proven to be a bad decision because it skips the cross-service authentication for the user.
This PR makes it so Credentials will handle _all_ redirects to the Learner Record MFE when appropriate. This solves an issue learners are experiencing when they are trying to make an authenticated REST API request before they have been authenticated with the Credentials service (APER-2224).
**Run JavaScript tests locally …

fix: Allow Credentials to handle all redirects to the Learner Record MFE where appropriate

---

credentials/apps/records/api.py
credentials/apps/records/views.py

[Jira Ticket: APER-2217](https://2u-internal.atlassian.net/browse/APER-2217)
* when users send their program via email, we will now log the internal credential user id, program name + uuid, and the pathway in order to make our bug investigation easier. 
* use get_user_model to safely retrieve User data

fix: add console logging when user shares a program record via pathway

---

webpack.config.js

Temporary change that is a test fix for APER-2210. I read that if `publicPath` is set in a webpack config then `django-webpack-loader` will use `publicPath` over the static URL settings. I think this could be the source of the problem with some of our assets being accessed at an incorrect URL.
I'm making this change based on a conversation here: https://github.com/django-webpack/django-webpack-loader/issues/107, specifically:
```
@mik3y Preferring publicPath over django's storage is a feature and the only way to give preference to django's storage right now is to omit publicPath from your webpack config like you correctly pointed out.
```

temp: omit publicPath from webpack.config.js

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

This PR updates our base.in requirement file to include the edx-event-bus-kafka package. This will be required to prepare the Credentials IDA for event bus functionality in the future.

chore: Add event bus requirements to Credentials

---

credentials/apps/core/api.py
credentials/apps/core/tests/factories.py
credentials/apps/core/tests/test_api.py
credentials/apps/credentials/api.py
credentials/apps/credentials/apps.py
credentials/apps/credentials/management/commands/consume_events.py
credentials/apps/credentials/signals.py
credentials/apps/credentials/tests/test_api.py
credentials/apps/credentials/tests/test_signals.py

[APER-2345]
Adds support for Credentials to consume the `CERTIFICATE_CREATED` event from the event bus.

feat: Consume `CERTIFICATE_CREATED` events using the event bus

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Pinning the version of edx-event-bus-kafka until we can update Credentials to work with the latest version and its breaking changes.

chore: pin edx-event-bus-kafka to 3.9.6 to avoid breaking changes

---

credentials/apps/core/management/commands/sync_ids_from_platform.py
credentials/apps/core/management/commands/tests/test_sync_ids_from_platform.py

This PR creates a management command that loops over all of the users in Credentials that don't have LMS user ids, fetches them from the LMS, and updates them in Credentials.
This will backfill all of the missing IDs that predate the update to collect LMS ids when data is pushed to Credentials.

feat: Management command to sync LMS user ids

---

credentials/apps/verifiable_credentials/admin.py
credentials/apps/verifiable_credentials/apps.py
credentials/apps/verifiable_credentials/checks.py
credentials/apps/verifiable_credentials/composition/__init__.py
credentials/apps/verifiable_credentials/composition/open_badges.py
credentials/apps/verifiable_credentials/composition/schemas.py
credentials/apps/verifiable_credentials/composition/utils.py
credentials/apps/verifiable_credentials/composition/verifiable_credentials.py
credentials/apps/verifiable_credentials/issuance/__init__.py
credentials/apps/verifiable_credentials/issuance/main.py
credentials/apps/verifiable_credentials/issuance/models.py
credentials/apps/verifiable_credentials/issuance/renderers.py
credentials/apps/verifiable_credentials/issuance/serializers.py
credentials/apps/verifiable_credentials/issuance/status_list.py
credentials/apps/verifiable_credentials/issuance/utils.py
credentials/apps/verifiable_credentials/permissions.py
credentials/apps/verifiable_credentials/rest_api/urls.py
credentials/apps/verifiable_credentials/rest_api/v1/urls.py
credentials/apps/verifiable_credentials/settings.py
credentials/apps/verifiable_credentials/signals.py
credentials/apps/verifiable_credentials/storages/__init__.py
credentials/apps/verifiable_credentials/storages/status_list.py
credentials/apps/verifiable_credentials/storages/utils.py
credentials/apps/verifiable_credentials/toggles.py
credentials/apps/verifiable_credentials/urls.py
credentials/settings/base.py
credentials/settings/private.py.example
credentials/settings/test.py
credentials/urls.py

**Note:**  for the sake of review effort simplification, it is decided to split this large PR onto 2 parts: 
- initial part - introduces a feature flag with a new application modules structure
- main part - adds all the implementation logic
This is the part 1/2 of the Verifiable Credentials feature.
Related PRs:
- [2nd part](https://github.com/openedx/credentials/pull/2001)
- [documentation](https://github.com/openedx/credentials/pull/1991)
- [configuration](https://github.com/openedx/configuration/pull/6928)
----
---
- Relates to https://github.com/openedx/frontend-app-learner-record/pull/151

feat: [FC-0006] add Verifiable Credentials optional feature

---

docs/conf.py
requirements/common_constraints.txt
requirements/docs.in
requirements/docs.txt

The edx-sphinx theme is being deprecated, and replaced with sphinx-book-theme.
This removes references to the deprecated theme and replaces them with the new
standard theme for the platform.
See openedx/edx-sphinx-theme#184

chore: Switch from edx-sphinx-theme to sphinx-book-theme

---

credentials/apps/credentials/rest_api/v1/tests/test_views.py
credentials/apps/credentials/rest_api/v1/views.py
credentials/apps/records/api.py

Add an optional section to the input payload for the learner status API which can provide a list of course-run UUIDS.
The API will handle either courses, course-runs, or a combination of both. (or none, but it won't do anything useful)

feat: add course_runs option in learner status API

---

credentials/apps/credentials/api.py
credentials/apps/credentials/tests/test_api.py

[APER-2505]
This PR corrects an error in the `_update_or_create_credential` function, which is invoked when processing `CERTIFICATE_CREATED` events from the event bus.
I had set the search criteria too strictly and didn't properly pass in a `defaults` dict with the data that should be updated if a match is found. This was resulting in a database IntegrityError because the ORM wasn't finding existing entities correctly and attempting to insert a new record that violated constraints on the table.

fix: correct use of `update_or_create` when updating existing credentials via event bus

---

credentials/apps/credentials/api.py
credentials/apps/credentials/tests/test_api.py

[APER-2505]
This PR fixes an issue that can come up when trying to retrieve an existing CourseCertificate object. Originally, we were using the `course_run` field to do the lookup but sometimes this data isn't set properly when it is created (which is a known issue and we're tracking this internally as APER-1777).
Instead, we should use the `course_id` field (which is really the course run key) to do the lookup.
This also fixes some errors in our unit tests that were setting the wrong data through use of our test data Factories.

fix: fix lookup of `CourseCertificate` objects

---

requirements/constraints.txt

Pinning version of `mysqlclient` to v2.1.1. See [APER-2556](https://2u-internal.atlassian.net/browse/APER-2556) for more details and plan for follow up.

fix: pin mysqlclient version

---

credentials/apps/api/v2/urls.py
credentials/apps/api/v2/views.py
credentials/apps/credentials/rest_api/urls.py
credentials/apps/credentials/rest_api/v1/views.py
credentials/apps/credentials/urls.py
credentials/urls.py

This API contains a non-CRUD class with no serializer, which the
swagger conversion can't handle automagically. Additionally, there was
an endpoint that had been imported twice because of a file structure
containing multiple `urls.py` files.
* specifies the swagger schema for a non-serializer class
* removes redunandant route via wrong endpoint
Note that the generated swagger document is somewhat confusing, and does not
correctly group the different APIs. This is unavoidable because of two
separate complicating factors:
* the openAPI specification, which cannot has certain assumptions about base prefix
* changes within this cluster of APIs, in which endpoint structure has had three
distinct layouts, before we reached the current, edx-standard structure.
(`appname/api/v#/endpoint_name`, …

fix: broken swagger and duplicate route

---

Dockerfile
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

[APER-2556]
This PR makes an update to the Credentials IDA's Dockerfile to install `pkg-config` which is required for `mysqlclient` v. 2.2.0+. This allow us to remove our constraint for the `mysqlclient` version installed with Credentials.

fix: update Dockerfile and unpin mysqlclient

---

.github/workflows/push-docker-image.yml

In this PR i updated github action to push multi-architecture(amd-64, arm-64) docker images on the docker hub. Now the M1/M2 apple machines would pull the arm-64 architecture docker images via devstack.

Docker multi-arch images push for linux/amd64, linux/arm64

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

This was producing filenames like `b'something'.csv` rather than just `something.csv`. The test didn't catch it because it just repeated the same code it was testing. There's randomness in the test data, so this uses a regex to get as close as possible to an equality assertion.

fix: Don't encode to bytes for CSV filename

---

credentials/apps/api/v2/serializers.py

[APER-2730]
It is difficult to determine exactly what is going wrong when grade data is different between the LMS and Credentials. This PR adds some logging to the `UserGradeSerializer` so that we have a bit more visibility into the updates being received from the LMS.

feat: add logging to Credentials grade endpoint

---

credentials/apps/credentials/config.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/signals.py
credentials/apps/credentials/tests/factories.py
credentials/apps/credentials/tests/test_issuer.py
credentials/apps/credentials/tests/test_signals.py
credentials/settings/base.py

[APER-2626]
- Adds support for the `PROGRAM_CERTIFICATE_AWARDED` event, emit when a program certificate is generated for a learner
- Adds default settings for the (redis) event bus to `base.py`
- Adds unit tests for the `_emit_program_certificate_signal` function of `../credentials/issuers.py`
- Slight refactor of the `issue_credential` function for readability
- Add additional doc updates where possible
- Adds unit tests for the new signal receivers in `../credentials/signals.py`

feat: add support for program certificate event bus events

---

credentials/apps/records/urls.py

The Program Dashboard from the LMS still uses a Credential URL path to allow users to view their Program Record. When the old Program Record view was deleted in #2104 , the URL path to `/records/programs/` was also removed, which prevented learners from viewing their Program Record through the Program Dashboard page. They were still able to see their record via the Profile MFE, because that path used the Learner Record MFE to view render the new Program Record page.  
Bring back the URL path handler (`/records/programs/{PROGRAM_UUID}`)and redirect it to the Learner Record MFE's Program Record page. 

fix: add back in program record URL handling

---

credentials/apps/credentials/management/commands/populate_missing_courserun_info.py
credentials/apps/credentials/management/commands/tests/test_populate_missing_courserun_info.py

When this code switched from using direct ORM calls to the catalog API, the exception handling that was there became meaningless and the error protection was no longer valid.
This fixes the code and adds a test case. While writing test cases to improve coverage for a few of the other exception handling cases, I realized that those exceptions were already handled by database constraints, so I removed the error handling code altogether.
FIXES: APER-2425

feat: fixing an exceptional case

---

credentials/apps/records/tests/test_utils.py
credentials/apps/records/utils.py

* switch away from logger.exception (which was logging the noisy stacktrace as well as the log message) to logger.debug (because this is expected behavior and we don't want to see messages about it under normal conditions)
* Adding a test to verify
FIXES: APER-718

feat: adds a test for missing program cert record

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

[APER-2847]
The latest version (5.3.0) of `social-auth-app-django` introduces a few migrations that can cause out-of-memory problems if the Credentials `social_auth_usersocialauth` table is large.
For now, we are pinning this package to an earlier version before the problematic migrations are introduced (5.2.0).
For more info, see: https://github.com/python-social-auth/social-app-django/issues/501

chore: pin `social-auth-app-django` to 5.2.x

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Temporarily unpinning `social-auth-app-django` so we can attempt to reverse the migration adding the `extra_data_new` column.

fix: unpin social auth

---

credentials/settings/devstack.py

- PR created under the issue https://github.com/openedx/credentials/issues/2144 to migrate credentials devstack cache backend from `MemcachedCache` to `PyMemcacheCache`

build: migrate devstack cache backend

---

credentials/settings/devstack.py

This PR fixes the name of a keyword argument set in the `OPTIONS` dictionary for the cache configuration in the devstack settings.

fix: fix keyword arg name in cache options

---

credentials/apps/catalog/admin.py

[APER-2841](https://2u-internal.atlassian.net/browse/APER-2841)
This PR updates the Catalog app's models available via Django Admin of the Credentials IDA to be read-only. We are making this change becuase Credentials is not the source of truth for this data, it is synced from the Course-Discovery IDA.
If the data needs to be updated, it should be done in Discovery and then admins should use the `copy-catalog` management command to sync the data to Credentials.
This is being done to ensure data integrity across services.

feat: make catalog model fields read only in Django Admin

---

credentials/apps/catalog/admin.py

This PR removes a field that was accidentally duplicated when displaying program data via Django admin.

fix: remove duplicated field displayed in django admin for programs

---

credentials/apps/api/v2/filters.py
credentials/apps/api/v2/serializers.py
credentials/apps/api/v2/tests/test_serializers.py
credentials/apps/api/v2/tests/test_views.py
credentials/apps/catalog/tests/test_api.py
credentials/apps/credentials/api.py
credentials/apps/credentials/management/commands/populate_missing_courserun_info.py
credentials/apps/credentials/management/commands/tests/test_populate_missing_courserun_info.py
credentials/apps/credentials/models.py
credentials/apps/credentials/rest_api/v1/tests/test_views.py
credentials/apps/credentials/tests/factories.py
credentials/apps/credentials/tests/test_api.py
credentials/apps/credentials/utils.py
credentials/apps/records/api.py
credentials/apps/records/management/commands/seed-records.py
credentials/apps/records/tests/test_utils.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/utils.py
credentials/apps/verifiable_credentials/rest_api/v1/tests/test_views.py
credentials/apps/verifiable_credentials/tests/test_utils.py

Will require thorough manual QA.
* on CourseCertificate save:
* create course_run from course ID if needed
* create course ID from course_run if needed
* refactored the CredentialField serializer to be more efficient given the change
* In most cases of direct object reference, switched from course_id to course_run.key
* Fixed a couple of bad tests that confused thought course_id should reference course_run.course.id (alas for legacy name issues)
* Cleaned up a few log messages (log levels, text, clarity, string formatting)
* marked some tests as skip
* Given the enforced save method, making objects broken enough to prove the test cases would require mocking so extreme as to make the tests practically useless
* The enforced data validation is tested elsewhere, by the rest of the test suite …

feat: enforce CourseCertificate course_run, course_id presence

---

Dockerfile
Makefile
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Install [`openedx-atlas`](https://github.com/openedx/openedx-atlas/#readme) as an alternative to Transifex `tx` client for managing translations when `OPENEDX_ATLAS_PULL` environment variable is set. This is similar to the [discovery atlas pull request](https://github.com/openedx/course-discovery/pull/4037).
```
cd ~/work/openedx/credentials
docker build --target=dev -t edxops/credentials:latest .
cd ~/work/openedx/devstack
make dev.remove-containers.credentials
make dev.up.credentials
docker-compose exec credentials atlas --version
docker-compose exec credentials env OPENEDX_ATLAS_PULL=true make pull_translations static.dev
docker-compose exec credentials ls -R credentials/conf
docker pull edxops/credentials:latest
make dev.shell.credentials
```
```
$ docker-compose exec credentials ls …
```

feat: use `atlas` in `make pull_translations`

---

credentials/apps/credentials/api.py
credentials/apps/credentials/signals.py
credentials/apps/credentials/tests/test_api.py
credentials/apps/credentials/tests/test_signals.py

[APER-2649]
This PR adds support for consuming `CERTIFICATE_REVOKED` events from the Event BUs to the Credentials IDA.
Additionally, there is a bit of cleanup and refactoring done to make consuming these events a bit more DRY.

feat: consume `CERTIFICATE_REVOKED` events from event bus

---

docs/event_bus.rst

[APER-2649]
This PR updates Credentials documentation to reflect the new ability to consume `CERTIFICATE_REVOKED` events.

docs: update Credentials docs for consuming `CERTIFICATE_REVOKED` events

---

credentials/settings/base.py
credentials/settings/production.py

Adding condition to load schemes as per django-version.
Related PR for https://github.com/edx/edx-internal/pull/9315/files

feat!: Django 4.0 and above, CSRF_TRUSTED_ORIGINS must include schemes

---

credentials/settings/base.py
credentials/settings/production.py

Merge this PR first https://github.com/edx/edx-internal/pull/9413/files. 
So that configs got available on argocd.
For Quince this cleanup require.

chore: using `CSRF_TRUSTED_ORIGINS` now. No need for extra variable.

---

credentials/apps/credentials/rest_api/v1/views.py
credentials/apps/credentials/utils.py
credentials/apps/records/management/commands/seed-records.py
credentials/apps/records/rest_api/v1/views.py
credentials/apps/records/utils.py
credentials/apps/records/views.py

[APER-2873]
A cleanup PR that refactors code in Credentials to use the `get_user_by_username` utility function over importing and using the User model directly.

refactor: update application code to use `get_user_by_username` utility function

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/settings/base.py
credentials/settings/devstack.py
credentials/settings/test.py
docs/learner_records.rst

[APER-2913]
This PR removes the `USE_LEARNER_RECORD_MFE` feature flag. This was originally used to gate redirections to the Learner Record MFE when it was under development.
The Learner Record MFE is now required for program record functionality, the legacy FE was removed as part of #2104 and #2106.

feat!: Remove unused feature flag

---

requirements/constraints.txt

[APER-2848]
The maintainers of `social-auth-app-django` have gone back and optimized the data migration and this _should_ (hopefully) resolve the problems we had upgrading to the latest version a few weeks back.

fix: remove social-auth constraint

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

fix: pin `social-auth-app-django` to 5.2.0... again

---

credentials/apps/api/v2/views.py
credentials/apps/core/api.py
credentials/apps/credentials/api.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py
credentials/apps/credentials/utils.py

[APER-3017]
Adds a feature to Credentials where the system will emit a Segment event (if configured) when a program credential is awarded or updated.
New events added with this PR:
* `edx.bi.credentials.credential_issuers.program_certificate_updated`
* `edx.bi.credentials.credential_issuers.program_certificate_created`
Additionally, an example of the properties sent with the event:
```
{
"category": "credentials",
"user":
{
"username": "edx",
"lms_user_id": 3
},
"program":
{
"uuid": "83c7ae34-5e74-44f1-a837-7eb3426b3478",
"title": "Best Program Ever",
"program_type": "microbachelors"
},
"uuid": "bd4ffd35-8c68-45c0-9eb8-9b8652411ba4",
"status": "awarded",
"url": "{blah}/credentials/bd4ffd358c6845c09eb89b8652411ba4/",
"timestamp": "2023-11-01T19:21:08.300353+00:00"
}
```
**Run JavaScript …

feat: emit Segment event when creating or updating a program credential

---

credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py

This is a fix for a recent change as part of PR #2276. We should pass the LMS User Id as `user_id` and not the `anonymous_id`.

fix: send lms_user_id as `user_id` and not `anonymous_id`

---

credentials/static/sass/_lib.scss
package-lock.json
package.json

Part of https://github.com/openedx/axim-engineering/issues/23
This replaces the `@edx/paragon` packag to point to the `paragon` package at
the `openedx` scope(`@openedx/paragon`). Imports have been updated to use the
same locations in the new package.

chore: Update to the new version of paragon in the new scope.

---

Dockerfile

In early October, we accepted an to the public Credentials Dockerfile presented through an OSPR. The purpose was to reduce the overall size of the Credentials Docker image.
However, shortly after this point, the Credentials image build started to fail.
The error we've been observing is...
```
#35 [linux/arm64 base  6/25] RUN npm install -g npm@9.x.x && npm cache clean --force;
#35 116.3 
#35 116.3 removed 16 packages, and changed 46 packages in 2m
#35 116.3 
#35 116.3 28 packages are looking for funding
#35 116.3   run `npm fund` for details
#35 136.6 npm WARN using --force Recommended protections disabled.
#35 152.1 npm ERR! code ENOTEMPTY
#35 152.1 npm ERR! syscall rmdir
#35 152.1 npm ERR! path /root/.npm/_cacache
#35 152.2 npm ERR! errno -39
#35 152.3 npm ERR! ENOTEMPTY: directory not …
```

fix: attempt to fix Credentials docker image build by reverting changes from #1912

---

credentials/apps/records/api.py
credentials/apps/records/tests/test_api.py

There are well documented communication issues between the LMS and Credentials systems. There are times that Credentials will just miss a grade update from the LMS. The grades stored in Credentials are used to render a learner's progress in their courses through the Learner Record UI.
This PR changes the behavior of the API that feeds data to the Learner Record MFE (program record page) and the Support Tools.
Previously, when rendering the program record page, if there are no grades available for a course (that is part of a program) we would show the course credential as "unearned".
This has caused a lot of confusion for our learners, as a missing grade in Credentials does not mean they haven't earned the certificate. In fact, most of the time, the learner has been able to view and share …

fix: display earned course credentials even if the grade is missing

---

credentials/apps/credentials/issuers.py
credentials/apps/records/views.py
credentials/settings/devstack.py
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

[APER-3056]
This PR features an upgrade of the Segment package in Credentials. The previous package (`analytics-python`) has been renamed, the previous package is no longer supported or under active development.
* Remove constraint on `analytics-python` in `constraints.txt`
* Remove the `analytics-python` package from `base.in`
* Adds the `segment-analytics-python` package to `base.in`
* Regenerate our requirements files after updates
* Update package imports where appropriate
* Fixes an unrelated issue where I was unable to create a shared program record with Credentials in devstack due to missing configuration

feat: update Segment package in Credentials

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.txt

[APER-2220] & [APER-2422]
Previously, upgrades to the `sphinx` and `urllib` packages had resulted in compatibility issues with other packages. These issues look to have been resolved and we are clear to upgrade them now.
* remove `sphinx` constraint and upgrade to the latest version
* remove `urllib` constraint and upgrade to the latest version

feat: remove constraints for 'sphinx' and 'urllib', upgrade to latest versions

---

requirements/constraints.txt

Upgrading `urllib3` to the 2.x versions introduced some weird issues with boto, causing an error to be thrown while rendering program credentials.

fix: (re)pin urllib to 1.x release

---

credentials/apps/records/views.py
credentials/settings/base.py
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

[APER-2169]
This PR removes a constraint on `django-ratelimit` in Credentials.

feat: upgrade `django-ratelimit' to 4.x

---

package-lock.json
package.json

[APER-2888]
The `codecov` package is EOL since January 2023 and we have moved to using a GitHub action for uploading coverage data. The NPM package can be removed from our requirements.

chore: remove unused `codecov` package from `package.json`

---

credentials/apps/records/api.py
credentials/apps/records/tests/test_api.py

This reverts commit c4ecb20e5a0ae569adeb7c84decc1c155f1d2521.

revert: display earned course credentials even if the grade is missing

---

credentials/apps/credentials/rest_api/v1/tests/test_views.py
credentials/apps/credentials/rest_api/v1/urls.py
credentials/apps/credentials/rest_api/v1/views.py
credentials/apps/records/api.py
docs/credentials_api.rst

Adds a bulk version of the learner_cert_status endpoint, following the pattern we use elsewhere for bulk variants: `bulk_learner_cert_status`.
Extrapolating the logic for a single learner/course combo into the API. Whether that particular structure belonged in api.py or in the specific API view is a matter of art rather than science; it felt like a more generalized function for the Python API rather than something for the view. (Reasonable developers could disagree; the specifics of the structure here are designed around the API view so you could go either way. To me it felt cleaner to leave it in `api.py`.)
This does have some repeated code as a side effect of not wanting to change the contract for the previously-existing endpoint, but it's kept to a minimum..
FIXES: APER-3102
**Run …

feat:  bulk learner cert status and point

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

we were assuming that segment was always being permitted from the browser side, but segment is blocked by every single privacy built in, including strict tracking protections in the browser. Allow download of the record in that case.
FIXES: APER-3164

feat: allow download of program record even when segment is blocked

---

credentials/apps/api/v2/decorators.py
credentials/apps/api/v2/tests/test_decorators.py
credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/views.py
credentials/settings/base.py

[APER-3122]
Adds a decorator that can be used to log incoming REST request data. This will be used to get more visibility into the grade updates flowing from the LMS to Credentials.
This functionality will be gated using a WaffleSwitch so that we don't cause a massive spike in log size. This is intended to be used for debugging when needed.

feat: add decorator that can be used to log incoming REST request data

---

credentials/apps/core/management/commands/tests/test_truncate_social_auth.py
credentials/apps/core/management/commands/truncate_social_auth.py
credentials/apps/core/tests/factories.py

truncates all entries in this table that were modified outside of the last 90 days. Doesn't take any arguments because YAGNI; can easily be modified in the future if the situation changes.
FIXES: APER-3160

feat: management command to truncate social auth

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

* now that we've truncated the old entries in usersocialauth, unpinning this dependency.
* Includes some requirements updates from `make upgrade`
If maintainers have migration failures on this upgrade, they should run `truncate_social_auth`:
https://github.com/openedx/credentials/blob/master/credentials/apps/core/management/commands/truncate_social_auth.py
This will remove all entries from the `usersocialauth` table that haven't been updated in 90 days, which makes the size of the table tractable for the dependency's migration.
FIXES: APER-3161

feat: unpin social auth django

---

.github/CODEOWNERS

we need to use the openedx group for any automated processes to work
FIXES: APER-3249

feat:  fixing broken CODEOWNERS

---

credentials/templates/base.html

[APER-3269]
This PR updates the base template for edX specific themed pages. The change adds a meta tag requesting robots not to index our program certificate pages.
The only pages rendered with this base template are certificates, all other learner-facing UI has been moved to the Learner Record MFE. 

feat: request robots to not index program certs

---

Dockerfile
minimal.yml

* pulling translations on docker build
FIXES: APER-3312

feat: atlas in dockerfile

---

credentials/conf/locale/config.yaml

* Although the directory for the unsupported language still exists in the code base, the [Makefile  deletes all committed locales](https://github.com/openedx/credentials/blob/781635ddb318312fbb7128252347cbaa0166c076/Makefile#L148-L149) before doing `atlas pull`, and the language in question is not currently pulled:
https://github.com/openedx/credentials/blob/781635ddb318312fbb7128252347cbaa0166c076/Makefile#L148-L149
FIXES: APER-3345

feat:  updating locale file for unsupported language

---

Makefile
credentials/settings/base.py
credentials/templates/_actions.html
credentials/templates/base.html
package-lock.json
package.json
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip.txt
requirements/production.txt
requirements/test.txt
requirements/translations.txt

The Credentials IDA gives our users the ability to share or print their program certificates if they wish. This functionality is enabled by rendering icons (provided via a third party package called `fontawesome`).
Recently, something caused this functionality to break and the icons are rendering as squares.
This PR attempts to fix this issue. Initially, we attempted to troubleshoot the original issue with the old `fontawesome` package (which was released 7 years ago). We were unable to do that. Then, we tried to update to the latest version of fontawesome via NPM. This caused additional issues that weren't well understood. Finally, I have decided to remove the npm package in favor of a pip package that is designed to work specifically with Django.
Thus, this PR adds a new default …

fix: fix social media and sharing icons

---

.github/workflows/migrations-mysql8-check.yml

`python-xmlsec`'s current version 1.3.14 is causing some issues during the dependency installation stage of `mysql8-migrations-check`. This PR is to pin it to 1.3.13 for the time being until the issue can be resolved. 
https://github.com/xmlsec/python-xmlsec/issues/314

fix: pin python-xmlsec to earlier version in mysql8-migrations-check

---

credentials/apps/catalog/api.py
credentials/apps/credentials/models.py
credentials/apps/credentials/views.py
credentials/templates/_actions.html

* enable the Facebook sharing button for program certificate
* fixing the LinkedIn sharing button for program certificate, so that (like the course certificate sharing button) it attempts to auto populate the share dialogue on LinkedIn
* moving more of the complexity back into the Python and out of the django template, where it's harder to manage well
* added a tiny bit of type hinting just to make debugging easier
switches to using direct URL instead of SDK  for the Facebook share, so that it won't be blocked by even mildly private browser settings.
FIXES: APER-3333

feat:  enabling the fb program certificate share

---

.github/workflows/ci.yml
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.in
requirements/dev.txt
requirements/production.txt
requirements/test.txt
requirements/translations.txt
tox.ini

on 3.11.9 they have made some changes which is breaking some tests. django will release its fix on 6th may.
Related [PR](https://github.com/python/cpython/commit/f97f25ef5dfcdfec0d9a359fd970abd139cf3428)
This is the root [cause](https://github.com/django/django/pull/17979#issuecomment-2061194558).
Upcoming fix.
https://github.com/django/django/pull/17979#issuecomment-2061194558
Only coverage is failing.

build: adding python3.11 support.

---

Dockerfile

This PR will upgrade the version of Python used in docker images created from the public repos Dockerfile.
Upgrading the Python version is part of the changes for the Redwood release of Open edX.

build: upgrade Python version in Dockerfile

---

credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/conf/locale/eo/LC_MESSAGES/django.po
credentials/conf/locale/rtl/LC_MESSAGES/django.po

a re-factor to fix some of the other social sharing links had broken the Twitter link. This standardizes the link format for social sharing for the program certificates, and removes all of the parsing and conditionals  for those links from the template.
FIXES: APER-3417

feat: fix broken Twitter link

---

.github/workflows/push-docker-image.yml

There seems to be an issue installing a required dependency (`didkit`) for the `arm64` platform. Since one of the two platforms are failing, it causes the good image for the `linux/amd64` platform to not upload either.
This is keeping us from being able to push an updated Docker image running Python 3.11 to DockerHub and impeding Devstack developers.
We are under the impression that only 2U uses this Dockerfile and this shouldn't affect the larger community.
For additional details, please see the public Credentials issue: https://github.com/openedx/credentials/issues/2477.

feat!: suspend building Docker image for arm64

---

requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

This updates edx-django-utils to the newest version, which will enable us to enable RUM in program certs once @iamsobanjaved's work in https://github.com/edx/edx-internal/pull/10902 is complete.
(note we don't actually have to wait for that other PR to deploy credentials)
FIXES: APER-3470

feat:  prerequisite for RUM

---

credentials/settings/base.py

* enables the front end monitoring middleware
FIXES: APER-3470

feat:   use the frontendmonitoringmiddleware if configured

---

.github/workflows/migrations-mysql8-check.yml

fix: replace deprecated github actions

---

credentials/apps/api/v2/tests/test_serializers.py

we have a weird error condition happening sometimes when the certificate available date is missing. On the one hand, this test does not reveal the cause of the error condition, but on the other hand, is an important test to have.

test: adding a new test for missing certificate available date

---

Makefile
README.rst

A PR to cleanup the Credentials README. Additionally, this removes some Makefile targets that are no longer valid, their functionality had been removed in an earlier PR.

docs: update README and Makefile

---

credentials/apps/core/management/commands/make_is_active_match_platform.py
credentials/apps/core/management/commands/tests/test_make_is_active_match_platform.py

this creates a management command to synchronize is_active between LMS and credentials. It only goes in one direction (the learner on credentials to is_active = True if that is the case on LMS), because the alternative is not a problem and is much more costly to update.
FIXES: APER-3346

feat: management command to synchronize is_active

---

.github/workflows/push-docker-image.yml
requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip.txt
requirements/production.txt
requirements/test.txt

The maintainers of `didkit` have released an update that fixes an issue where it would not build on arm64-based systems.
This resolves an issue with Devstack and developers running devstack on Apple silicon-based machines.

feat: Re-enable Docker image builds for arm64

---

credentials/apps/core/management/commands/make_is_active_match_platform.py
credentials/apps/core/management/commands/tests/test_make_is_active_match_platform.py

the limitations of unit tests over integration tests! I was calling the wrong parameter in my tests, but my mocked API calls were returning what I thought I should be calling.
While I was in there I improved some error logic for learner inconsistency and added a new test for the improved error logic.

feat: fixing a bug that always assumed active status was true on LMS

---

credentials/settings/base.py

This repo is no longer using USE-JWT-COOKIE header, since it has the required edx-drf-extensions>10.2.0, where it was fully removed.
This is final clean-up for this repo.
See "[DEPR]: USE-JWT-COOKIE header" for more details:
- https://github.com/openedx/edx-drf-extensions/issues/371

feat: DEPR USE-JWT-COOKIE header

---

credentials/settings/base.py

Reverts openedx/credentials#2554
A similar PR may have broken edx-platform, so reverting until investigation has completed. See https://github.com/openedx/edx-platform/pull/35397

Revert "feat: DEPR USE-JWT-COOKIE header"

---

.github/workflows/migrations-mysql8-check.yml
Dockerfile

chore: upgrade workflows and Dockerfile to use ubuntu 24 LTS

---

credentials/apps/catalog/utils.py

chore: updating a docstring to match reality
this no longer uses an `EdxRestApiClient`. This is the last trace of the client; the defunct tests using it were deleted September 2023 (https://github.com/openedx/credentials/pull/2213)

remove traces of EdxRestApiClient

---

.github/workflows/migrations-mysql8-check.yml

This PR reintroduces the upgraded version of Ubuntu in CI workflows from PR #2556. Dockerfile updates will be reintroduced separate from this change.

fix: update version of ubuntu used in CI workflows

---

.readthedocs.yaml

Updates `.readthedocs.yml` to fix a broken build #2577
[Conifugration docs](https://docs.readthedocs.io/en/stable/config-file/v2.html)

fix: read the docs config

---

.readthedocs.yaml

Fix ubuntu version
Failing build: https://app.readthedocs.org/projects/edx-credentials/builds/25658228/

fix: read the docs ubuntu version

---

.readthedocs.yaml

Removed invalid `python.version` key
Failed build: https://app.readthedocs.org/projects/edx-credentials/builds/25658344/

fix: update RTD config

---

.readthedocs.yaml

Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html#packages
Failed build: https://app.readthedocs.org/projects/edx-credentials/builds/25671070/

fix: update rtd config path

---

credentials/templates/base.html

Fixes a typo in the `noindex` meta tag in the base program cert template. 

fix: fix typo in noindex meta tag

---

.readthedocs.yaml
pyproject.toml

Adds enough package information to pyproject.toml to allow setuptools to cope with the multiple top-level directories.
FIXES: APER-3700

fix:  fixing the failing readthedocs build

---

credentials/urls.py
credentials/views.py

The `mock-toggles` REST endpoint was used for testing a feature used by 2U for collecting the configuration of settings in OeX IDAs. The feature was never fully implemented in Credentials and this endpoint is no longer being used, so we are removing it.

feat!: remove mock toggle endpoint

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip.txt
requirements/production.txt
requirements/test.txt

Removing the constraint on `urllib3` no longer downgrades boto and its dependencies. I think it is safe to remove this constraint now.

chore: remove urllib3 constraint

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt
requirements/translations.txt

The `edx-i18n-tools` package has been upgraded and we no longer need this constraint.
Relevant `edx-i18n-tools` PR: https://github.com/openedx/i18n-tools/pull/146.

chore: remove `lxml` constraint

---

credentials/settings/base.py
credentials/settings/devstack.py
credentials/settings/local.py
credentials/settings/test.py

this is an attempt to fix the overrides for the log formatter by putting stubs in the settings files.

chore: fixing the stubs in the settings file for the log formatter

---

credentials/settings/base.py
credentials/settings/devstack.py
credentials/settings/local.py
credentials/settings/test.py

The previous attempt to set a local log format failed because first the base configuration files are applied, in which the logging format is set via a function call, and then our own internal overrides are applied. Basically, there's a timing problem.
This is an attempt to solve that problem in the hopes that the environment variables are set before the configuration files for the application are run. This change will be made in conjunction with an internal config PR.
FIXES: APER-3805

feat: attempting a new fix for the local log format problem

---

credentials/settings/production.py

Make sure that the call to `get_logger`  happens after the configuration file overrides have a chance to set `LOGGING_FORMAT_STRING`.
FIXES: APER-3805

chore: fix timing issue with logging overrides

---

credentials/apps/credentials_theme_openedx/static/sass/_print-rendering.scss
credentials/static/sass/_components.scss
credentials/static/sass/_config.scss
credentials/static/sass/_layouts.scss
credentials/static/sass/_lib.scss
package-lock.json
package.json

Updates Paragon to v23
The two big changes to Paragon that will effect this repo are the deprecation of FontAwesome support and the change from SCSS to CSS variables.
There were only two variables being pulled from paragon: `$spacer` and `$card-border-radius`
It's worth noting that there are still SCSS variables present in this repo, but that is because there is a `_utilities.scss` file that houses a number of SCSS variables used throughout other files ([source](https://github.com/openedx/credentials/blob/master/credentials/static/sass/_utilities.scss))
Example print preview of cert when on Paragon 23 in local environment:
[Professional Certificate _ Open edX.pdf](https://github.com/user-attachments/files/18769379/Professional.Certificate._.Open.edX.pdf)
**Run JavaScript tests locally …

chore: update paragon 23

---

credentials/settings/base.py

- PR created under the issue https://github.com/edx/edx-arch-experiments/issues/815
- The middleware was [deprecated/renamed](https://github.com/openedx/edx-drf-extensions/blob/2b4347518680046aa54caa404c030d0ffe308acf/CHANGELOG.rst#620---2020-08-24) in the `edx-drf-extensions==6.2.0` but was pending to be updated.

refactor: update deprecated requestmetric middleware

---

.github/workflows/ci.yml

the docs aren't building on github because a valid version of `didkit` won't install, and I think it might be because we upgraded Python to bleeding edge but only for the `ci` workflows.

chore: downgrading python in ci  for consistency

---

.github/workflows/upgrade-python-requirements.yml

I was fixing up some spacing/indentation in this workflow and accidentally de-dented the `secrets` portion of the job too far.

fix: fix indentation in the upgrade-python-requirements workflow

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip.txt
requirements/production.txt
requirements/test.txt

This constraint is no longer needed now that Credentials supports Python 3.12.

chore: remove constraint on edx-django-utils

---

credentials/settings/base.py
credentials/static/js/fontawesome.js
credentials/templates/base.html
package-lock.json
package.json
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip.txt
requirements/production.txt
requirements/test.txt
webpack.config.js

Previous to this change, when collecting static assets, we would include ALL of the FA icons. This PR is an attempt to limit the icons in our bundle to only the icons used in the UI.
As part of this change, the `fontawesomefree` app is no longer needed, so it has been removed.

feat: cherry pick FA icons used in Credentials UIs

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/pip.txt
requirements/pip_tools.txt
requirements/production.in
requirements/production.txt
requirements/test.txt

`newrelic` is not directly used by this repository, and edx-django-utils provides a pluggable telemetry API for any deployers who use New Relic.
See DEPR for details: https://github.com/openedx/public-engineering/issues
This PR is composed of two commits. The first is the result of `make upgrade`, and the second removes `newrelic` from the `.in` files and runs `make upgrade` again (so you can see the actual effect).
----

feat: Remove newrelic package from base dependencies

---

docs/badges/configuration/accredible.rst
docs/badges/configuration/credly.rst
docs/badges/examples.rst

Currently the links to the configuration examples are broken in https://docs.openedx.org/projects/edx-credentials/en/latest/badges/configuration/accredible.html and https://docs.openedx.org/projects/edx-credentials/en/latest/badges/configuration/credly.html. This PR fixes the broken links and uses RST best practice (reference links rather than direct filepaths).

docs: Fix cross-ref bug in badging docs
