credentials/settings/devstack.py

add devstack settings for docker usage

---

credentials/settings/devstack.py

Update debug settings for logger.
@awais786 @waheedahmed @ahsan-ul-haq @tasawernawaz

update logger import for devtsack

---

credentials/apps/api/tests/test_views.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py

Implement the https://openedx.atlassian.net/browse/ECOM-3324.
update the value of existing attribute or add a new one.

update duplicate attribute exists in db then update its value.

---

credentials/apps/credentials/utils.py

ECOM-3343
Adding sorting using same keys on list and groupby.

Adding sorting using same keys on list and groupby.

---

credentials/settings/base.py
credentials/settings/production.py
credentials/urls.py
docs/getting_started.rst
requirements/base.txt
requirements/production.txt

ECOM-3323
@awais786 @ahsan-ul-haq @tasawernawaz

add boto in prod requirements + add s3 storage settings for prod

---

Makefile

@zubair-arbi @awais786 @tasawernawaz

Add runserver in make file

---

Makefile

@zubair-arbi @tasawernawaz @awais786

changes in make file to remove test_root

---

docs/credential_api.rst
docs/index.rst

ECOM-3276
Added docs for POST and PATCH endpoints of user credential API.
Please review this. @zubair-arbi @awais786 @ahsan-ul-haq

Added docs for create and update user credentials API

---

docs/credential_api.rst

ECOM-3276
Adding documentation for credential List and Get endpoints.
Please review this, @awais786 @zubair-arbi @ahsan-ul-haq

Added docs for Get and List endpoints of credential APIs

---

credentials/apps/api/authentication.py
credentials/apps/api/jwt_decode_handler.py
credentials/apps/api/tests/mixins.py
credentials/apps/api/tests/test_authentication.py
credentials/apps/api/tests/test_views.py
credentials/apps/core/constants.py
credentials/apps/core/migrations/0002_auto_20160111_1251.py
credentials/apps/core/tests/factories.py
credentials/settings/base.py
credentials/settings/test.py
credentials/urls.py
requirements/base.txt

@zubair-arbi @tasawernawaz @awais786 
ECOM-3413

Added JWT authentication, initial roles

---

credentials/apps/core/migrations/0003_auto_20160114_1001.py

ECOM-3420
Added migration for credentials service user and permission for admin group.
Please review this.
@awais786 @ahsan-ul-haq @zubair-arbi

Added migration for service user and permissions for admin group.

---

credentials/apps/credentials/admin.py
credentials/apps/credentials/models.py

* added `uuid` field in `UserCredential`
* renamed `CourseCertificate` and `ProgramCertificate`
Please review this @awais786 @ahsan-ul-haq @zubair-arbi

update django admin

---

credentials/apps/credentials/__init__.py
credentials/apps/credentials/apps.py
credentials/apps/credentials/tests/mixins.py
credentials/apps/credentials/tests/test_apps.py
credentials/apps/credentials/tests/test_utils.py
credentials/apps/credentials/utils.py
credentials/settings/base.py
credentials/settings/local.py
credentials/settings/private.py.example

ECOM-3282
* Create settings variables required for communication with the `organizations` API in `LMS`
* Add `get_organization` method to get an organization from edx rest api client with the provided `organization_key`
* Add tests for data retrieval from `organizations` api
* Create settings variables required for communication with the `user` API in `LMS`
* Add `get_user` method to get a user data from edx rest api client with the provided `username`
* Add tests for data retrieval from`users` api
For LMS checkout this PR to add JWT auth: https://github.com/edx/edx-platform/pull/11211

get organization and user data from lms

---

credentials/apps/core/context_processors.py
credentials/apps/core/tests/test_context_processors.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/templates/base.html
credentials/templates/credentials/program_certificate.html
credentials/templates/credentials/render_credential.html
credentials/templates/credentials/view_certificate.html

ECOM-3445
Adding the back-end view code for rendering the template. For the time being we don't have any HTML so I just pass the values into the template. Also Code is written in way that it loads the relevant html file depending on the content type.

Adding rendering views.

---

credentials/apps/credentials/admin.py
requirements/base.txt

* Display hex of uuid on the Admin panel
* Add python-memcached requirements
@zubair-arbi @tasawernawaz @awais786 please review.

Update admin to show hex value of UUID and update requirements

---

credentials/apps/credentials/fixtures/sample_data.json
credentials/apps/credentials/tests/test_fixtures.py
docs/getting_started.rst

ECOM-3482
* Added fixture file with sample data
* Added test for preventing fixture from getting stale.
@zubair-arbi @awais786 @ahsan-ul-haq

Added fixture for sample data

---

credentials/templates/credentials/program_certificate.html

At the moment in header logo is appearing from organizations.  
I have replaced this with edx-logo.

Update the header logo.

---

credentials/apps/core/views.py
credentials/templates/base.html
credentials/templates/credentials/program_certificate.html

* Fix multiple body tag issue due to which `xseries` watermark was not showing
* Minor change in `500` view response code

fix multiple body tag issue

---

docs/getting_started.rst

ECOM-3618
@zubair-arbi @tasawernawaz @awais786

docs for credentials service user

---

Makefile
acceptance_tests/config.py
acceptance_tests/mixins.py
acceptance_tests/pages.py
acceptance_tests/test_auth.py
requirements/test.txt

[ECOM-3695](https://openedx.atlassian.net/browse/ECOM-3695)
* added `make accept` command for running acceptance tests.
* added acceptance tests for auth.
@awais786 @zubair-arbi @ahsan-ul-haq @waheedahmed

Added acceptance tests for auth

---

credentials/settings/production.py

@maxrothman: Review?
@zubair-arbi: FYI
@jimabramson: FYI

Add a default value for FILE_STORAGE_BACKEND

---

requirements/monitoring/requirements.txt

Added requirements monitoring file

---

docs/testing.rst

ECOM-3518
* added docs for acceptance.

Added docs for acceptance tests.

---

acceptance_tests/config.py
acceptance_tests/mixins.py
acceptance_tests/pages.py
acceptance_tests/test_rendering.py

For theses tests data should be exists in lms and programs. 
1. In LMS user should have completed x-series program.
2. In test case it will try to try to credential. If test case already exist then will change in db. Then test in a test user will login on lms and from dashboard it will click the credential link.  
3. In other test case first credentials will be revoked and then again user will login and in this case there will be no credential.

Acceptance test to view credential

---

Makefile

@zubair-arbi @tasawernawaz @jimabramson FYI.

Remove prod-requirements Make target

---

credentials/settings/production.py

@maxrothman please review. @zubair-arbi FYI.

Set COMPRESS_STORAGE equal to STATICFILES_STORAGE

---

credentials/settings/production.py

@e0d @maxrothman
FYI @zubair-arbi

Allow app to start when STATICFILES_STORAGE is undefined

---

requirements/base.txt

Upgrade Django to 1.8.10

---

acceptance_tests/config.py
acceptance_tests/pages.py

ECOM-3850
On Stage there is basic authentication is on. Adding its authentication.

Adding basic auth code for acceptance tests.

---

credentials/apps/credentials/admin.py
credentials/apps/credentials/forms.py

ECOM-3880
@awais786 @tasawernawaz @waheedahmed 
Add multiline titles for signatories through signatories django admin.

support multiline titles for the signatories

---

credentials/apps/credentials/tests/test_views.py
credentials/templates/credentials/program_certificate.html

ECOM-3949
@awais786 @tasawernawaz please review

Show organization short name instead of name

---

credentials/apps/credentials/migrations/0002_signatory_organization_name_override.py
credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_views.py
credentials/templates/credentials/program_certificate.html

ECOM-4009
@awais786 @tasawernawaz please review.

Add signatory organization info

---

credentials/static/sass/_print-rendering.scss
credentials/static/sass/_views.scss
credentials/templates/credentials/program_certificate.html

ECOM-3781
Fixing print preview back-ground image issue.

Fixing print issue.

---

requirements/base.txt

This version of the package stores the token_type in the User.extra_data. 
ECOM-4263

Updated edx-auth-backends to 0.2.1

---

requirements/base.txt

upgrade to address vulnerability http://www.cvedetails.com/cve/CVE-2016-2533/ and others
@clintonb @rlucioni @zubair-arbi FYI.

Update Pillow to 3.1.1

---

requirements/base.txt

ECOM-4249
@awais786 @ahsan-ul-haq @tasawernawaz @waheedahmed 
https://docs.djangoproject.com/en/1.8/releases/1.8.13/

Upgrade Django to 1.8.13

---

acceptance_tests/pages.py
acceptance_tests/test_rendering.py

Credentials acceptance test are updated according to UI changes in LMS dashboard. 
This PR will be merged after this [PR](https://github.com/edx/edx-platform/pull/12468) (Containing changes in learner's dashboard) in edX platform.
Please review this @awais786 @waheedahmed @zubair-arbi @ahsan-ul-haq

Credentials acceptance tests updated.

---

acceptance_tests/config.py
acceptance_tests/mixins.py
credentials/apps/api/authentication.py
credentials/apps/api/tests/test_authentication.py
credentials/settings/base.py
docs/testing.rst
requirements/base.txt

Implementing Bearer Authentication.
Update the acceptance test cases.
Add unit test cases.

Awais786/ecom 3808 Implement Bearer Auth for acceptance tests.

---

requirements/base.txt

@awais786 @ahsan-ul-haq @tasawernawaz @waheedahmed @clintonb

update django-waffle to 0.11.1

---

credentials/settings/base.py
requirements/base.txt

[TE-1500](https://openedx.atlassian.net/browse/TE-1500)

Add edx-django-release-util

---

requirements/base.txt

Upgrade to Django 1.8.14

---

.travis.yml
Makefile
requirements/local.txt

Updated i18n-tool version, .travis.yml and Makefile files changed

---

requirements/base.txt

Updated to Django 1.8.16

---

requirements/optional.txt

ECOM-6316
@rlucioni for review
FYI @edx/ecommerce

Update New Relic Agent to avoid bug

---

requirements/base.txt

Updated Pillow

---

credentials/apps/credentials/management/commands/add_uuids_to_program_certificates.py

ECOM-6485
@edx/ecommerce 
Please review
thanks

Added mgmt command to add UUIDs to program certificates table.

---

credentials/settings/base.py
credentials/settings/devstack.py
credentials/settings/local.py
credentials/settings/private.py.example
credentials/settings/test.py

This data type allows us to include additional custom apps from YAML in production.
ECOM-4639

Converted INSTALLED_APPS setting from a tuple to a list

---

credentials/apps/edx_credentials_extensions/migrations/0001_initial.py
credentials/settings/base.py

Docker devstack updates

---

requirements/base.txt
requirements/docs.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

Upgraded to Django 1.9

---

credentials/static/sass/_lib.scss
requirements/base.txt

Fixed SASS issue

---

credentials/apps/core/management/commands/create_or_update_site.py
credentials/apps/core/tests/test_commands.py
docs/credentials_admin.rst

@mjfrey Here's the command that should be ran to update SiteConfiguration with WL specific information. I would like to get some feedback whether or not I'm on the right track here. There's a to-do list below showing what needs to be done before this can be merged.
JIRA story: https://openedx.atlassian.net/browse/ECOM-7453
To-do:

[ECOM-7453] Enable Configuration of a White Label site

---

credentials/settings/base.py
credentials/static/sass/_components.scss
credentials/static/sass/_lib.scss
credentials/static/sass/_ltr.scss
credentials/static/sass/_rtl.scss
credentials/static/sass/main-ltr.scss
credentials/static/sass/main-rtl.scss
credentials/templates/base.html
credentials/templates/credentials/programs/base.html
requirements/base.txt

Corrected RTL SASS

---

.eslintrc.json
Makefile
credentials/apps/credentials/views.py
credentials/static/js/analytics.js
credentials/static/js/sharing.js
credentials/templates/_actions.html
credentials/templates/credentials/base.html
gulpfile.js
package.json

A tracking event is now sent to Segment when a user clicks any of the share buttons. This will allow us to track usage of these buttons.
ECOM-6578

Firing analytics events when share buttons clicked

---

requirements/base.txt

Upgrade Django to 1.9.13

---

openedx.yaml

Update repo owner to edx/learner

---

Makefile

Ignoring SCSS files for collectstatic

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/views.py
credentials/settings/production.py

Updates for multi-tenancy

---

credentials/settings/base.py
requirements/base.txt

This should alleviate the CORS issues in our deployment environments.
LEARNER-516

Added django-cors-headers

---

credentials/static/js/analytics.js
credentials/static/js/sharing.js

@clintonb this doesn't feel right, but it's causing linting failures on master.

Fix JS linting failure

---

requirements/base.txt

Bump credentials-theme version

---

requirements/base.txt

theme version bump

---

requirements/base.txt

version bump for themes

---

Makefile

Prevent migrate target from prompting for input

---

requirements/base.txt

Upgraded edx-auth-backends to 1.0.2

---

credentials/apps/core/tests/test_models.py
credentials/settings/base.py
requirements/base.txt

Corrected paths for social-django

---

requirements/base.txt

Upgraded edx-auth-backends

---

requirements/base.txt

Upgraded edx-auth-backends to 1.1.2

---

credentials/apps/core/migrations/0002_auto_20160111_1251.py
requirements/base.txt

LEARNER-480
Subtask: LEARNER-948
Upgrading Django version for Credential service from 1.9.13 to 1.10.7

Upgraded to Django 1.10

---

credentials/apps/api/accreditors.py
credentials/apps/api/tests/test_accreditors.py

- Changed quote style
- Inverted if-else
- Moved attributes outside of setUp()

Minor improvements

---

requirements/base.txt

Release notes at https://docs.djangoproject.com/en/1.11/releases/1.11.3/
@edx/learner FYI

Upgrade Django to 1.11.3

---

credentials/settings/devstack.py

- Corrected default value of SOCIAL_AUTH_EDX_OIDC_URL_ROOT
- Added SOCIAL_AUTH_EDX_OIDC_ISSUER

Resolved OpenID Connect issues on devstack

---

requirements/production.txt

Upgrade New Relic agent

---

requirements/base.txt

LEARNER-2326
We needed to update the MM logo on certificates to include the RegisteredTrademark Symbol
@edx/learner  Please review

Update to use the credential-themes library version 0.1.5

---

credentials/static/js/analytics.js
credentials/templates/_analytics.html

**JIRA tickets**: [LEARNER-1778](https://openedx.atlassian.net/browse/LEARNER-1778)
Fix tracking id of the user to None
**Description**
If the user is not logged-in,credential service should not emit
a user identifier.In order to do this, tracking id of the user is
changed to 'None' instead of emitting 'credentials-None'

Fix user's credential identifier to None

---

credentials/templates/credentials/programs/base.html

This resolves a cosmetic issue that has bugged me for weeks!

Added missing space

---

credentials/settings/production.py

[LEARNER-3052](https://openedx.atlassian.net/browse/LEARNER-3052)

read config file strings as unicode

---

requirements/base.txt

Updates the credentials_themes dependency to pull in Spanish translations.

Update credentials_themes dependency

---

credentials/apps/credentials/models.py

@McKenzieW Should we be changes the key here, or changing it on discovery?

Fixed key for hours of effort

---

requirements/base.txt

related to https://github.com/edx/credentials-themes/pull/26

bump credentials themes version to 0.1.11

---

requirements/local.txt

updated edx-i18n-tools version to latest.

LEARNER-3461 edx-i18n-tools-version-update

---

requirements/base.txt

Updated edx-auth-backend version.

---

docs/theming.rst

JIRA: https://openedx.atlassian.net/browse/LEARNER-3834

Add docs for i18n/theming

---

requirements/base.txt

Bump credentials-themes to 0.1.12

---

requirements/base.txt

FYI: @edx/learner-spartans @edx/learner

UPdated opaque keys package

---

docs/internationalization.rst

Updates the i18n docs with information about:
- Language resolution
- Internationalized Program Certificates
- Translation management
JIRA: https://openedx.atlassian.net/browse/LEARNER-2987

i18n docs for language resolution, program certs, and translation mgt

---

docs/configuring_certificates.rst
docs/index.rst

https://openedx.atlassian.net/browse/LEARNER-3836

Added documentations for enabling hours of effort

---

requirements/base.txt

Bump credentials-themes to 0.1.14 to release new SysEng certs

Version bump of credentials-themes

---

.travis.yml
Makefile
requirements/local.txt

Updated travis to use the i18n-tools validate
to validate translations in pullrequests.
LEARNER-2556

Updated travis validate translations

---

requirements/base.txt
requirements/local.txt

This fixes sandboxes/production. Whoops.

Move statici18n requirement

---

openedx.yaml

We probably want this in Hawthorn, so tagging it for inclusion.

Tag for inclusion in Open edX releases

---

credentials/apps/core/views.py

This reverts commit a5e29b6a6e05873894a56704b835ade513def8e5.

Revert "Dont"

---

requirements/base.txt

Bump credentials version for new MIT themes

Bump credentials-themes to 0.1.15

---

docs/decisions/0001-record-architecture-decisions.md
docs/decisions/0002-front-end-technologies.md
docs/decisions/0003-copy-core-data-locally.md
docs/decisions/0004-filter-lms-side.md

These are all credentials-wide, but app-specific docs could also be added in the future.

Add some local decision docs

---

requirements/base.txt

Updates credentials-themes to 0.1.16

Update credentials-themes to 0.1.16

---

credentials/apps/records/management/commands/seed-records.py

**Ticket:** https://openedx.atlassian.net/browse/LEARNER-5577

LEARNER-5577 Management command to seed db with fake data

---

credentials/apps/credentials/models.py
credentials/apps/credentials/tests/test_models.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py

Subtitle is needed for some WL program certificates.

Add program subtitle to cert context.

---

Makefile
package-lock.json

With less devDependencies this time.

Update package-lock again

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

Fix for [LEARNER-5624](https://openedx.atlassian.net/browse/LEARNER-5624)
Updates records logic to include all cert statuses (AWARDED or REVOKED), only verified grades are used.
Updates course name and key to the course _run_ name and key
Updates issue date to refer to the user_credential modified date
Updates Program ordering on the _get_programs() to sort programs by name
Updates course-run ordering to use the ordering from Programs SortedManytoMany field

Updated records log to include all cert statuses

---

requirements/base.txt

Update themes version to 0.1.18
https://github.com/edx/credentials-themes/releases/tag/0.1.18
WL-1681

Update themes version to 0.1.18

---

package-lock.json
package.json

Fix cannot resolve svg-inline-loader.

---

.travis.yml
Dockerfile
Makefile
docker-compose.travis.yml

Switching from using (and building) `devstack-slim` to `latest`.

Switch Docker Container to the configuration one.

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/tests/utils.py
requirements/test.txt

Attempts to fix some flaky tests in records/test_views.py.  Additionally, adds in Random State logging to aid future debugging of these tests (When they inevitably still fail 🙃 )

Update some flaky tests

---

credentials/apps/catalog/admin.py

Deleted code that registered the models.
LEARNER-5588

Hides catalog models from django admin. 

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/components/specs/ShareProgramRecordModal.test.jsx

- Updated backend to get parameters from body
- Updated backend to return full url instead of just uuid
- Updated front end to read this url

Updated request/response format for share modal

---

package-lock.json

Reverted package-lock.json file to e83d953a9ad6dfcbf2d561eafeb3bf6308fa471d in attempt to fix:
"ERROR in ./credentials/static/sass/main-rtl.scss", 
"Module build failed: ModuleBuildError: Module build failed: ", 
"$custom-control-indicator-checked-disabled-bg:  rgba(theme-color(\"primary\"), .5) !default;", 
"                                               ^", 
"      Argument `$color` of `rgba($color, $alpha)` must be a color",

Revert package-lock.json

---

credentials/apps/records/models.py

Fix issue where certificate field was erroneously deleted a release too early.

Revert early removal of certificate field

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/api/v2/views.py
credentials/settings/base.py

Add rate limiting to the GradeViewSet and CredentialViewSet credentials endpoints.  Please view the comments of [LEARNER-5587](https://openedx.atlassian.net/browse/LEARNER-5587) for a discussion of the chosen thresholds.

LEARNER-5587

---

credentials/settings/devstack.py

This fixes the bug where logging out in credentials would get a 404

Fix devstack logout url

---

credentials/static/components/ProgramRecord.jsx
credentials/static/components/RecordsHelp.jsx
credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/sass/views/_program-record.scss
credentials/static/sass/views/_records-list.scss

Fix some accessibility issues in credentials documented [here](https://openedx.atlassian.net/browse/LEARNER-5976)
The only visually noticeable change is that the green "Completed" badge is now a darker shade of green.

A11y fixes

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

We were using the wrong issue date for course certificates in the program record view. Now we use the visible_date attribute that the LMS provides.
And flesh out support for visible_date by not showing certs as awarded until the date has passed.
https://openedx.atlassian.net/browse/LEARNER-5995

Show actual issue date

---

credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py
credentials/static/components/ProgramRecord.jsx

[LEARNER-5986](https://openedx.atlassian.net/browse/LEARNER-5986)
Adds metadata to the record data csv

Add user metadata to CSV

---

docs/internationalization.rst

[LEARNER-6068](https://openedx.atlassian.net/browse/LEARNER-6068)

Add developer instructions for docker translation management and update i18n link

---

credentials/static/js/test/fixtures/analytics.html
credentials/static/js/test/specs/analytics_spec.js
credentials/templates/_actions.html

[LEARNER-5739](https://openedx.atlassian.net/browse/LEARNER-5739)

Recategorize certificate sharing analytics events

---

credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/sass/views/_program-record.scss

[LEARNER-6134](https://openedx.atlassian.net/browse/LEARNER-6134)
**UI**
Send modal
Share modal

Fix checkbox and url alignment in program records modals

---

credentials/settings/base.py
requirements/base.txt

Add metrics for requests.

---

docs/analytics.rst
docs/credentials_api.rst
docs/internationalization.rst
docs/testing.rst

Updates:
- internationalization.rst  - [LEARNER-6108](https://openedx.atlassian.net/browse/LEARNER-6108)
- analytics.rst - [LEARNER-6118](https://openedx.atlassian.net/browse/LEARNER-6118)
- credentials_api.rst - [LEARNER-6105](https://openedx.atlassian.net/browse/LEARNER-6105)
- testing.rst - [LEARNER-6106](https://openedx.atlassian.net/browse/LEARNER-6106)

Some docs updates

---

credentials/apps/catalog/management/commands/copy_catalog.py
credentials/settings/base.py
docs/credit_pathways.rst
docs/getting_started.rst
docs/index.rst
docs/program_records.rst

And a few miscellaneous fixes along the way.
https://openedx.atlassian.net/browse/LEARNER-6110
---
- UI Changes

Add records documentation for admins

---

acceptance_tests/pages.py
acceptance_tests/provision.sh
acceptance_tests/runserver.sh
acceptance_tests/runtests.sh
acceptance_tests/test_credentials.py
acceptance_tests/test_records.py
credentials/apps/records/management/commands/seed-records.py
credentials/settings/_debug_toolbar.py
credentials/settings/local.py
credentials/static/components/ProgramRecord.jsx
credentials/static/components/RecordsList.jsx
credentials/static/sass/views/certificate.scss
credentials/templates/base.html

Add some checks for the new records pages.
This does a few more things around the place too, will add per-line comments.
https://openedx.atlassian.net/browse/LEARNER-6162
---
- UI Changes

Add acceptance tests for Records

---

credentials/apps/catalog/management/commands/copy_catalog.py
credentials/apps/catalog/tests/test_commands.py

Use new pathways endpoint instead.

---

credentials/apps/catalog/management/commands/copy_catalog.py
credentials/apps/catalog/models.py
credentials/apps/catalog/tests/test_commands.py

Stop filtering out unpublished runs

---

credentials/apps/catalog/tests/test_commands.py
credentials/apps/catalog/tests/test_utils.py
credentials/apps/catalog/utils.py

Pull in pathway_type field data from discovery.

---

credentials/apps/credentials_theme_openedx/static/sass/_build.scss
credentials/apps/credentials_theme_openedx/static/sass/_components-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_layouts-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_print-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_print.scss
credentials/apps/credentials_theme_openedx/static/sass/_utilities.scss
credentials/static/sass/_components.scss
credentials/static/sass/_layouts.scss
credentials/static/sass/_print-rendering.scss
credentials/static/sass/_print.scss
credentials/static/sass/_utilities.scss
credentials/static/sass/views/certificate.scss

Add temporary variables until upgrade when we can remove.
https://openedx.atlassian.net/browse/LEARNER-6320
---
- UI Changes

Change edx-pattern grayscale to bootstrap 4.1 grayscale.

---

credentials/apps/credentials_theme_openedx/static/sass/_utilities.scss
credentials/static/sass/_utilities.scss

Add $white and $black vars.

---

requirements/base.txt

Bump version of credentials-themes.

---

credentials/apps/credentials_theme_openedx/static/sass/_components-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_print-rendering.scss
credentials/apps/credentials_theme_openedx/static/sass/_print.scss
credentials/apps/credentials_theme_openedx/static/sass/_utilities.scss
credentials/static/sass/_components.scss
credentials/static/sass/_print-rendering.scss
credentials/static/sass/_print.scss
credentials/static/sass/_utilities.scss

https://openedx.atlassian.net/browse/LEARNER-6333
---
- UI Changes

Change fonts from edx-pattern to bootstrap.

---

requirements/base.txt

Bump themes version.

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/records/tests/test_views.py
credentials/shared/log_checker.py

Remove rate limit tests that have become flaky.

---

credentials/templates/credentials/programs/base.html

https://openedx.atlassian.net/browse/LEARNER-5661
---
- UI Changes

Update certificate base.html to include multiple orgs.

---

credentials/apps/credentials/views.py

Update example cert org string.

---

credentials/apps/api/authentication.py
credentials/settings/base.py
requirements/base.txt

ARCH-255: update legacy imports

---

requirements/base.txt

Bump version

---

credentials/apps/credentials/templatetags/html.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials_theme_openedx/templates/openedx/credentials/programs/professional-certificate/certificate.html
credentials/settings/base.py
credentials/templates/404.html
credentials/templates/500.html
credentials/templates/_actions.html
credentials/templates/_footer.html
credentials/templates/credentials/programs/base.html
credentials/templates/management.html
credentials/templates/programs.html
credentials/templates/records.html
requirements/base.txt

Remove code related xss escaping functions from
credentials codebase and now using functions
from xss-utils package. Also removing custom
filters to builtin django filters.
[LEARNER-6686](https://openedx.atlassian.net/browse/LEARNER-6686)

Use xss-utils pkg for script escaping functions.

---

requirements/local.txt

---
- UI Changes 
Install `pyinotify` in Linux development environments to improve the efficiency of `runserver`'s file change polling.

TE-2791 More efficient change polling in dev environments

---

credentials/apps/records/management/commands/seed-records.py
credentials/static/components/MasqueradeBanner.jsx
credentials/static/components/ProgramRecord.jsx
credentials/static/components/RecordsHelp.jsx
credentials/static/components/RecordsList.jsx
credentials/static/components/SendLearnerRecordModal.jsx
credentials/static/components/ShareProgramRecordModal.jsx
credentials/static/components/specs/ProgramRecord.test.jsx
credentials/static/sass/_layouts.scss
credentials/static/sass/views/_program-record.scss
credentials/static/sass/views/_records-list.scss

Learner Records style fixups

---

requirements/base.txt

Update edx-credentials-themes to the bootstrap version

---

requirements/base.txt

Updated credentials-themes version in base.txt

Updated Credentials-theme package version

---

openedx.yaml

Add a tag.

---

README.rst
credentials/apps/api/v2/tests/test_serializers.py
requirements/base.txt

Upgrade DRF to 3.9.4

---

requirements/base.txt

unpin django

---

credentials/settings/base.py
credentials/settings/devstack.py
credentials/settings/test.py

Move credentials defaults from configration repo

---

requirements/base.txt

Updating credentials-themes to 0.1.29

---

credentials/apps/credentials_theme_openedx/static/sass/_print-rendering.scss

Program certificate print preview is loading in vertical instead of horizontal like course certificate.
PROD-492
---
- UI Changes

Fix program certificate print view.

---

requirements/base.txt

@edx/masters-neem 
https://openedx.atlassian.net/browse/EDUCATOR-4551
cc @feanil

Upgrade Django to 1.11.23 for security fixes

---

openedx.yaml

Update openedx.yaml for Masters squad reorg

---

credentials/apps/records/messages.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/utils.py
credentials/apps/records/views.py

Revert "Changed from_address while sending email to partner"

---

credentials/apps/catalog/admin.py

Create the admin section for the Cache app because we needed to adjust some data in this app for support
---

Add the admin section for the Catalog Cache

---

credentials/apps/catalog/admin.py

I should've taken @kdmccormick's advice on my last PR.
This PR is to improve the view of the credentials admin so we can do search and have a nice table view.
---
@kdmccormick and @mikix Please help review again.

Add better admin table data for search and viewing

---

credentials/apps/records/messages.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/utils.py
credentials/apps/records/views.py
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt

learner email added in reply_field

---

credentials/settings/credentials.yml

Added devstack config yml file to app repo

---

credentials/apps/api/permissions.py
credentials/apps/catalog/models.py
credentials/apps/core/migrations/0001_initial.py
credentials/apps/core/models.py
credentials/apps/credentials/migrations/0001_initial.py
credentials/apps/credentials/models.py
credentials/apps/records/models.py

JIRA Link: [BOM-1171](https://openedx.atlassian.net/browse/BOM-1171)

BOM-1171 : Django 2.2 Upgrade via CodeMods

---

credentials/settings/base.py

Move default variables from config repo

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Relevant JIRA issue can be found [here](https://openedx.atlassian.net/browse/BOM-1275).

Removed the constraint for edx-ace - BOM-1275

---

.travis.yml
Makefile
requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/django.txt
requirements/docs.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.in
requirements/test.txt
tox.ini

JIRA: [BOM-1351](https://openedx.atlassian.net/browse/BOM-1351)
- Added django 2.x workers to travis

BOM-1351: Added django 2.x workers to travis 

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Downgrade social-auth-core to work around permission loss

---

.travis.yml
tox.ini

Relevant JIRA : [https://openedx.atlassian.net/browse/BOM-1523](https://openedx.atlassian.net/browse/BOM-1523)

BOM-1523 : Added Python 3.8 To Travis Tests

---

requirements/all.txt
requirements/base.txt
requirements/dev.in
requirements/dev.txt
requirements/docs.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt

pyinotify was causing performance issues with django 2.2 in development environments.
---
- UI Changes

Switch from pyinotify to pywatchman for filemonitoring.

---

gulpfile.js
package-lock.json
package.json

Update Gulp to 4.0.2 version so our translation job can succeed here.
---
@kdmccormick and @edx/masters-devs-cosmonauts Please review.

Upgrade gulp to 4.0.2

---

acceptance_tests/e2e/pages.py
credentials/apps/credentials/issuers.py
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt

**Issue:** [BOM-1808](https://openedx.atlassian.net/browse/BOM-1808)
- Removed usage of package `six`.

Removed usage of package six

---

credentials/apps/records/views.py
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

https://openedx.atlassian.net/browse/BOM-1864
using django-ratelimit latest pypi release in credentials
---
- UI Changes

using django-ratelimit latest version

---

.gitignore
requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.in
requirements/test.txt

**Description:**
- Remove nose from requirements/test.in file.
- Update packages with "make upgrade"

[BD-18] Remove nose from requirements

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Unpin drf-jwt

---

credentials/apps/records/views.py

DE-1151:  add page url to Segment event.

---

.travis.yml

Remove invalid Travis keys

---

credentials/apps/catalog/tests/test_commands.py
credentials/apps/core/tests/test_models.py
credentials/apps/records/tests/test_views.py
credentials/apps/records/views.py

Fix warnings

---

README.rst

Remove link to google group and use consistent link style

---

requirements/base.in

Upgrade credentials-themes requirement to 1.30.1. After this is merged I'll run the upgrade job.

Upgrade credentials-themes requirement to 1.30.1

---

Makefile

Codecov was ignoring .py files. This attempts to fix that.
75 files added: https://codecov.io/gh/edx/credentials/pull/842/changes

Fix code coverage

---

credentials/apps/core/s3utils.py
requirements/production.in

Remove boto from s3utils. Also fix a typo.

MICROBA-628 Remove boto from s3utils

---

package-lock.json
package.json

When building PR #853 , the build failed with an error saying that this package was missing.

Add babel-loader to deps

---

Makefile
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

* Add _push_translations_ to makefile
* Get _help_ command in sync with other repos
* Upgrade _credentials-themes_ and run _make upgrade_
Note: edX seems inconsistent on the implementation of _push_translations_ and _pull_translations_ (sometimes we call the _i18n_tool_ and other times we call _tx_ directly). I picked the approach that seems more common (call _tx_ directly) but suggestions are welcome.

MICROBA-698 Add push_translations and upgrade credentials-themes

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.txt

Upgrade credentials-themes to 0.1.33 and run _make upgrade_.

MICROBA-698 Upgrade credentials-themes to 0.1.33

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Upgrade credentials-themes, and add bleach and django simple history

MICROBA-698 MICROBA-667 Upgrade credentials-themes

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

[MICROBA-654]
- Upgrade credentials-themes to 0.1.36

MICROBA-654 | Upgrade credentials-themes to 0.1.36

---

credentials/apps/records/views.py
credentials/static/components/ProgramRecord.jsx
credentials/templates/_base_style.html
credentials/templates/base.html
package-lock.json
package.json

to the Base style of the Learner records.

[MICROBA-744] Changes to apply the themed styles from Credentials themes

---

credentials/static/components/RecordsList.jsx

Screenshot with 1 button showing the hover state.

[MICROBA-744] Update button to use bootstrap class

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

[MICROBA-744] Merging updates from Credentials-themes and other python

---

package-lock.json
package.json

For [MICROBA-640](https://openedx.atlassian.net/browse/MICROBA-640) (and [MICROBA-882](https://openedx.atlassian.net/browse/MICROBA-882)).
Upgrade to patch security vulnerability.

MICROBA-640 Upgrade axios

---

package-lock.json
package.json

Upgrade `karma`; one of several upgrades toward [MICROBA-640](https://openedx.atlassian.net/browse/MICROBA-640).
Upgrading from `1.7.1` -> `5.2.3`!
Changelog here: http://karma-runner.github.io/5.0/about/changelog.html
- `3.0.0` drops support for Nodejs4
- `4.0.0` drops support for Node 6
- `5.0.0`:
- Karma plugins which rely on the fact that Karma uses Bluebird promises may break as Bluebird-specific API is no longer available on Promises returned by the Karma core
- server: Deprecated createPreprocessor removed, karma-browserify < 7 version doesn't work
- no more testing on node 8.
Addresses:
```
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial …
```

MICROBA-640 Upgrade karma

---

package-lock.json
package.json

[MICROBA-910](https://openedx.atlassian.net/browse/MICROBA-910)
- Updating from `1.1.2` -> `2.0.3`
- Changelog: [https://github.com/karma-runner/karma-coverage/blob/master/CHANGELOG.md](https://github.com/karma-runner/karma-coverage/blob/master/CHANGELOG.md)
Addresses:
```
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ karma-coverage [dev] …
```

MICROBA-910 Upgrade karma-coverage

---

package-lock.json
package.json

First step toward [MICROBA-914](https://openedx.atlassian.net/browse/MICROBA-914).
- Updating from `2.7.0` -> `3.0.0` (I’m upgrading one major version at a time on this one; trying to get to v4)
- Migration guide: https://webpack.js.org/migrate/3/ (There are apparently no breaking changes between v2 and v3 🤞)

MICROBA-914 Upgrade webpack (to 3.0.0, step 1)

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.txt

version pin ticket: https://openedx.atlassian.net/browse/MICROBA-929

social-auth-core <4.0.3 constraint

---

.dockerignore
.eslintrc.json
Dockerfile-testing
Makefile
credentials/static/components/MasqueradeBanner.jsx
credentials/static/components/ProgramRecord.jsx
credentials/static/components/RecordsList.jsx
credentials/static/components/Utils.jsx
credentials/static/js/analytics.js
package-lock.json
package.json

Updating gulp-eslint for security. As it's a testing requirement, if tests pass, then we're probably okay :)

Update gulp-eslint package

---

requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

Revert "Python Requirements Update"

---

credentials/apps/api/v2/tests/test_views.py
credentials/apps/credentials/issuers.py
credentials/apps/credentials/tests/test_issuer.py

This reverts commit 58f6ba6c8eef4ee845bc6dc2ab23275bfe2fca5f.

Revert 58f6ba6c

---

credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py

Second attempt at [MICROBA-994](https://openedx.atlassian.net/browse/MICROBA-994).
Instead of using lazy translations, use [`django.utils.translation.override`](https://docs.djangoproject.com/en/2.2/ref/utils/#django.utils.translation.override) to tell the view which language to use when translating.
**The problem**
One particular string on program certificates configured to use Spanish is not being translated into Spanish.
**The solution**
That particular string is constructed in the view rather than the template. It was getting translated before/without knowing what language is set from the program certificate configuration. Now, we’re making sure it knows which language it should use.

MICROBA-994 Override with configured certificate language in view

---

requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt

Release notes: https://github.com/jazzband/pip-tools/releases/tag/6.0.0

Bump credentials-themes version

---

.github/CODEOWNERS

build: Add codeowners file to help with PR notifications

---

credentials/apps/credentials/admin.py

By finding the matching ProgramCertificate and CourseCertificates ahead
of time, we avoid the multilayer joins that were causing performance
issues.
Our slow query in prod will go from:
```
SELECT COUNT(*) AS `__count` 
FROM `credentials_usercredential` 
LEFT OUTER JOIN `credentials_programcertificate` 
ON (
`credentials_usercredential`.`credential_id` = `credentials_programcertificate`.`id` 
AND 
(`credentials_usercredential`.`credential_content_type_id` = %s)
) 
LEFT OUTER JOIN `catalog_program` 
ON (`credentials_programcertificate`.`program_id` = `catalog_program`.`id`) 
LEFT OUTER JOIN `credentials_coursecertificate` 
ON (
`credentials_usercredential`.`credential_id` = `credentials_coursecertificate`.`id` 
AND 
(`credentials_usercredential`.`credential_content_type_id` = %s)
) 
LEFT …
```

[perf] Minimize joins in UserCred list view

---

credentials/apps/credentials/utils.py

This commit updates / adds some utility methods to use our new
certificate_available_date field on `CourseCertificate` (instead of the
visible_date on `UserCredentialAttribute`) for the visible date passed to
the frontend UI elements; specifically for "Date Earned" for course
certificates on the program record page (/records/programs/
<program_uuid>), and for the "Issued" date on program certificates
(/credentials/<program user credential uuid>).
This work is gated behind the `USE_CERTIFICATE_AVAILABLE_DATE` toggle
while development is in progress.
In partial fulfillment of [MICROBA-1170](https://openedx.atlassian.net/browse/MICROBA-1170) and [MICROBA-1171](https://openedx.atlassian.net/browse/MICROBA-1171).
- This doesn’t yet replace _all_ the places where the old `visible_date` is used; …

feat: use certificate_available_date field for UI

---

.github/workflows/upgrade-python-requirements.yml

JIRA: https://openedx.atlassian.net/browse/BOM-2598

feat: Added upgrade-requirements workflow

---

credentials/apps/credentials/utils.py

Addresses MICROBA-1303, which was made from CR-3802. A learner’s program
certificate was showing an issue date earlier than expected, earlier
than the date when they completed all the required courses.
This was because of some faulty logic in our
`_get_program_certificate_visible_date` method. It was only returning
the latest associated `certificate_available_date`. But
`certificate_available_dates` are only set on courses that are
instructor-paced and have a certificate availability date manually set.
In the case of our learner, only one course in the program had a
`certificate_available_date`--and it was one of the earlier courses
completed by the learner. The rest of the courses did not have a
`certificate_available_date` because they were self-paced. Since the
logic only returned the …

fix: update program credential visible date logic

---

credentials/apps/catalog/api.py
credentials/apps/catalog/tests/test_api.py
credentials/apps/credentials/api.py
credentials/apps/credentials/data.py
credentials/apps/credentials/tests/test_api.py
credentials/apps/records/rest_api/urls.py
credentials/apps/records/rest_api/v1/serializers.py
credentials/apps/records/rest_api/v1/tests/test_serializers.py
credentials/apps/records/rest_api/v1/tests/test_views.py
credentials/apps/records/rest_api/v1/urls.py
credentials/apps/records/rest_api/v1/views.py
credentials/apps/records/tests/test_utils.py
credentials/apps/records/urls.py
credentials/apps/records/utils.py
credentials/apps/records/views.py

[MICROBA-1318]
new program record REST API endpoint for Learner Record MFE
Changed API fields to show enrolled programs using old code
Moved existing functionality to common utility file
Added Python API methods
added unit tests

feat: new program record REST API endpoint for Learner Record MFE

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt

Manual python upgrade and moved social-auth-app-django to common constraint file

chore: Manual python upgrade and moved social-auth-app-django to common

---

package-lock.json
package.json
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/pip_tools.txt
requirements/production.txt
requirements/test.txt
webpack.config.js

Downgrade CSS loader and update mime type to woff2 fonts. Bumps
credentials-themes where the same changes were made.

fix: downgrade css-loader and fix woff2 fonts

---

.github/workflows/ci.yml
.readthedocs.yml
Makefile
docs/conf.py
docs/decisions.rst
docs/index.rst
docs/testing.rst
requirements/docs.in
requirements/docs.txt
tox.ini

* Test docs build as a part of CI
* Correct issues that were causing the docs build to fail.
* Move readthedocs config to `.readthedocs.yml`

docs: Fix Docs Build

---

credentials/apps/core/models.py
credentials/apps/core/tests/test_models.py
credentials/apps/credentials/tests/test_views.py
credentials/apps/credentials/views.py
credentials/templates/credentials/programs/base.html

[MST-895](https://openedx.atlassian.net/browse/MST-895)
If user has chosen to use their verified name on certificates, use the verified name when rendering a program certificate.

feat: use verified name on program certificate

---

credentials/settings/devstack.py

[MICROBA-1438]
* Update learner record MFE ports to 1990 for local development

fix: Update learner record MFE port for local/devstack development

---

Makefile
credentials/apps/api/tests/mixins.py
requirements/all.txt
requirements/base.txt
requirements/common_constraints.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

This Upgrade PR contains breaking changes due to pyjwt==2.1.0 and edx-drf-extensions latest version.
This PR needs proper testing on stage.

feat!: upgrade pyjwt to 2.1.0

---

credentials/apps/credentials/docs/decisions/0002-user-credential-date-override.rst

Add ADR for Certificate Date Override changes.
Toward [MICROBA-1399](https://openedx.atlassian.net/browse/MICROBA-1399).

docs: Certificate Date Override ADR

---

credentials/apps/core/utils.py
credentials/settings/base.py

A small function that populates the LMS user-id when a user logs into
credentials for the first time. This will only update the lms_user_id
for users that specifically go to credentials; either to their records
page or otherwise. This will not update for users who are awarded a
prgram/course credential.

[feat] MB-1464: Add lms_user_id

---

credentials/apps/core/management/commands/sync_lms_user_ids.py

[MICROBA-1465]
- add new management command that will sync lms_user_id data from a temp table to the core_user table of the Credentials IDA

feat: add new management command that will sync lms_user_id data from a temp table

---

.github/workflows/upgrade-python-requirements.yml

Update schedule to better match EST employees

chore: Change requirements job schedule

---

requirements/base.in

* Upgrade credentials-themes to v. 0.1.102.

chore: bump `credentials-themes` version to 0.1.102

---

.github/workflows/migrations-mysql8-check.yml

build: Adding migrations check for mysql8
https://openedx.atlassian.net/browse/BOM-3279

build: Adding migrations check for mysql8.

---

credentials/settings/base.py
credentials/urls.py
requirements/all.txt
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/production.txt
requirements/test.txt

This PR was created from [PR](https://github.com/openedx/credentials/pull/1502) in order to solve  conflicts with versions dependencies

[Draft]feat: update drf_yasg library for python 38

---

credentials/urls.py

- Enables the CSRF endpoint in Credentials

feat: enable CSRF endpoint to support the Learner Record MFE

---

credentials/apps/records/views.py

The Credentials IDA has a feature that allows you to download a CSV representation of your public Program Records.
In our development environment (devstack) this functionality is broken because we are trying to make an analytics call to Segment with an ID retrieved from a cookie in our web request. This cookie exists in our Stage and Production environments but does not exist in development environments. This causes an exception to be thrown.
I decided on this fix over exception handling because it seems like a better backup in case this other cookie doesn't exist and will allow us to continue tracking these analytics/events via Segment in our live systems.

fix: Download Record/CSV creation broken in development environments

---

credentials/static/components/SendLearnerRecordModal.jsx
credentials/static/components/specs/SendLearnerRecordModal.test.jsx

[APER-1965](https://2u-internal.atlassian.net/browse/APER-1965) Styling bug for the checkboxes on Send Record modal
Added `Form.CheckboxSet` wrapper around checkboxes and updated change event accordingly

Paragon CheckboxSet style fix

---

catalog-info.yaml

Add Backstage config

---

.github/workflows/add-to-project.yml

Try out an action to add pull requests and issues to the credentials project.

build: an action to auto-add issues and PRs to a project.

---

Dockerfile

chore: Remove maintainer line

---

.github/workflows/add-to-project.yml
catalog-info.yaml

The OSPR bot will now add pull requests to projects if directed to by catalog-info.yaml.

build: switch to new bot-based add-pr-to-project

---

.github/workflows/push-docker-image.yml

Reverts openedx/credentials#1926

Revert "chore(deps): update docker/build-push-action action to v4"

---

codecov.yml
credentials/apps/plugins/apps.py
credentials/apps/plugins/constants.py
credentials/settings/base.py
credentials/settings/devstack.py
credentials/settings/production.py
credentials/settings/test.py
credentials/urls.py

feat: [FC-0006] add plugins support

---

docs/decisions/0007-learner-status-endpoint.rst

ADR for new endpoint to provide learner status for a given list of courses.

docs: 0007-learner-status-endpoint.rst

---

docs/credentials_api.rst

* adding the new endpoint to the docs
FIXES: APER-2529

feat: add new endpoint to readthedocs

---

.github/workflows/push-docker-image.yml

Description: There was some issue with the tag command which was not allowing docker multi-arch images to build and single arch image was building, I fix the issue in this PR.

Fix for docker multi-arch image

---

requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

This reverts commit 91bd64a354c3fd7e55f24c4319ac89ecc750152f.

Revert "fix: unpin social auth (#2167)"

---

.github/workflows/ci.yml
credentials/apps/api/urls.py
credentials/apps/api/v2/urls.py
credentials/apps/core/__init__.py
credentials/apps/core/admin.py
credentials/apps/credentials/__init__.py
credentials/apps/credentials/rest_api/urls.py
credentials/apps/credentials/rest_api/v1/urls.py
credentials/apps/credentials/urls.py
credentials/apps/edx_django_extensions/tests/test_views.py
credentials/apps/edx_django_extensions/urls.py
credentials/apps/records/rest_api/urls.py
credentials/apps/records/urls.py
credentials/apps/verifiable_credentials/rest_api/urls.py
credentials/apps/verifiable_credentials/urls.py
credentials/settings/test.py
credentials/urls.py
tox.ini

Executing codemodes django42.
Note:
Owning team can review and test before merge.

fix: adding django42 support.

---

docs/verifiable_credentials/quickstart.rst

This PR fixes the numbered list in the credentials docs.

docs: fixed numbered list

---

Makefile
requirements/all.txt
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt
requirements/translations.txt

Upgrading to edx-i18n-tools==1.3.0

chore: using new version of i18.

---

package.json

Paragon adds what it needs
FIXES: APER-2920

feat:  removing unnecessary bootstrap

---

Dockerfile

Related to https://github.com/openedx/devstack/issues/1220

Update watchman version

---

credentials/apps/core/management/commands/tests/test_truncate_social_auth.py
credentials/apps/core/management/commands/truncate_social_auth.py

* improved test coverage
* in doing so, found & fixed a bug, yay tests
* and slightly re-factored when test complexity made apparent mild algorithmic complexity
FIXES: APER-3198

feat:  improve test coverage

---

.github/workflows/upgrade-python-requirements.yml

on github, the group has a lowercase `u`.
FIXES: APER-3306

feat:  changing the case of the group to notify

---

.github/workflows/migrations-mysql8-check.yml
Dockerfile

This reverts commit 93c00e615ac4f4c0a6f0cde15092132481b565dc.
The Dockerfile changes appear to be causing a permissions issue. I will reintroduce the workflow changes in CI separate from the Dockerfile update.

revert: revert "chore: upgrade workflows and Dockerfile to use Ubuntu 24 LTS (#2556)"

---

.github/workflows/ci.yml

Remove duplicate test step, use new Codecov action style.

build: Update codecov

---

docs/verifiable_credentials/tech_details.rst
requirements/all.txt
requirements/base.txt
requirements/dev.txt
requirements/production.txt
requirements/test.txt

This is a fix for ARM64 builds (CI or for a local development).

build(deps): update didkit version to 0.3.3

---

credentials/apps/edx_credentials_extensions/migrations/0001_initial.py
docs/internationalization.rst

Ref https://github.com/openedx/edx-documentation/issues/2339

docs: Update outdated link target URLs

---

.github/workflows/ci.yml
.github/workflows/migrations-mysql8-check.yml
.github/workflows/upgrade-python-requirements.yml
.readthedocs.yaml
tox.ini

add Python 3.12 support
